AWSTemplateFormatVersion: '2010-09-09'
Description: Sysdig Secure Onboarding
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sysdig Assigned Settings (Do not change)
      Parameters:
      - NameSuffix
      - ExternalID
      - TrustedIdentity
      - IsOrganizational
      - OrganizationalUnitIDs
    ParameterLabels:
      NameSuffix:
        default: Name Suffix
      ExternalID:
        default: External ID
      TrustedIdentity:
        default: Trusted Identity
      IsOrganizational:
        default: Is Organizational
      OrganizationalUnitIDs:
        default: Organizational Unit IDs
Parameters:
  NameSuffix:
    Type: String
    Description: Suffix to append to the resource name identifiers
    AllowedPattern: '[0-9a-z]+'
    MaxLength: 8
    MinLength: 4
  ExternalID:
    Type: String
    Description: Sysdig assigned token that proves you own this account
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  IsOrganizational:
    Type: String
    Description: Install into an organization
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  OrganizationalUnitIDs:
    Type: CommaDelimitedList
    Description: Comma separated list of organizational unit IDs to deploy
Conditions:
  IsOrganizational:
    Fn::Equals:
    - Ref: IsOrganizational
    - 'true'
Resources:
  ConfigPostureRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sysdig-secure-posture-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Ref: TrustedIdentity
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/SecurityAudit
      Policies:
      - PolicyName: !Sub sysdig-secure-posture-${NameSuffix}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: elasticfilesystem:DescribeAccessPoints
            Resource: '*'
          - Effect: Allow
            Action:
            - waf-regional:ListRules
            - waf-regional:ListRuleGroups
            Resource:
            - arn:aws:waf-regional:*:*:rule/*
            - arn:aws:waf-regional:*:*:rulegroup/*
          - Effect: Allow
            Action: macie2:ListClassificationJobs
            Resource: '*'
          - Effect: Allow
            Action:
            - lambda:GetRuntimeManagementConfig
            - lambda:GetFunction
            Resource: '*'
          - Effect: Allow
            Action: account:GetContactInformation
            Resource: '*'
  OnboardingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sysdig-secure-onboarding-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Ref: TrustedIdentity
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
      ManagedPolicyArns:
        Fn::If:
        - IsOrganizational
        - - arn:aws:iam::aws:policy/AWSAccountManagementReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - - arn:aws:iam::aws:policy/AWSAccountManagementReadOnlyAccess
  OrganizationStackSet:
    Type: AWS::CloudFormation::StackSet
    Condition: IsOrganizational
    Properties:
      StackSetName: !Sub sysdig-secure-organization-${NameSuffix}
      Description: Creates IAM roles within an AWS organization
      PermissionModel: SERVICE_MANAGED
      Capabilities:
      - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 90
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
      Parameters:
      - ParameterKey: NameSuffix
        ParameterValue:
          Ref: NameSuffix
      - ParameterKey: TrustedIdentity
        ParameterValue:
          Ref: TrustedIdentity
      - ParameterKey: ExternalID
        ParameterValue:
          Ref: ExternalID
      StackInstancesGroup:
      - DeploymentTargets:
          OrganizationalUnitIds: !Ref OrganizationalUnitIDs
        Regions:
        - Ref: AWS::Region
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role for Agentless
        Parameters:
          NameSuffix:
            Type: String
            Description: Suffix to append to the resource name identifiers
            AllowedPattern: "[0-9a-z]+"
            MaxLength: 8
            MinLength: 4
          TrustedIdentity:
            Type: String
            Description: Trusted identity
          ExternalID:
            Type: String
            Description: external ID

        Resources:
          ConfigPostureRole:
            Type: "AWS::IAM::Role"
            Properties:
              RoleName: !Sub sysdig-secure-posture-${NameSuffix}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Effect: "Allow"
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Action: "sts:AssumeRole"
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
              ManagedPolicyArns:
              - arn:aws:iam::aws:policy/SecurityAudit
              Policies:
              - PolicyName: !Sub sysdig-secure-posture-${NameSuffix}
                PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                  - Effect: "Allow"
                    Action: "elasticfilesystem:DescribeAccessPoints"
                    Resource: "*"
                  - Effect: "Allow"
                    Action:
                    - "waf-regional:ListRules"
                    - "waf-regional:ListRuleGroups"
                    Resource:
                    - "arn:aws:waf-regional:*:*:rule/*"
                    - "arn:aws:waf-regional:*:*:rulegroup/*"
                  - Effect: "Allow"
                    Action: "macie2:ListClassificationJobs"
                    Resource: "*"
                  - Effect: "Allow"
                    Action:
                    - "lambda:GetRuntimeManagementConfig"
                    - "lambda:GetFunction"
                    Resource: "*"
                  - Effect: "Allow"
                    Action: "account:GetContactInformation"
                    Resource: "*"
          OnboardingRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub sysdig-secure-onboarding-${NameSuffix}
              AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Action: sts:AssumeRole
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
              ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AWSAccountManagementReadOnlyAccess

Outputs:
  ConfigPostureRoleARN:
    Description: ARN of the config posture role
    Value:
      Fn::Sub: ${ConfigPostureRole.Arn}
  OnboardingRoleARN:
    Description: ARN of the onboarding role
    Value:
      Fn::Sub: ${OnboardingRole.Arn}
