AWSTemplateFormatVersion: '2010-09-09'
Description: Sysdig Secure Onboarding
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sysdig Assigned Settings (Do not change)
      Parameters:
      - NameSuffix
      - ExternalID
      - TrustedIdentity
      - IsOrganizational
      - OrganizationalUnitIDs
      - Partition
      - RootOUID
      - IncludeOUIDs
      - ExcludeOUIDs
      - IncludeAccounts
      - ExcludeAccounts
    ParameterLabels:
      NameSuffix:
        default: Name Suffix
      ExternalID:
        default: External ID
      TrustedIdentity:
        default: Trusted Identity
      IsOrganizational:
        default: Is Organizational
      OrganizationalUnitIDs:
        default: (Deprecated, use RootOUID or IncludeOUIDs instead) Organizational Unit IDs
      Partition:
        default: AWS Partition
      RootOUID:
        default: Root Organization Unit ID
      IncludeOUIDs:
        default: Include Organizational Unit IDs
      ExcludeOUIDs:
        default: Exclude Organizational Unit IDs
      IncludeAccounts:
        default: Include AWS accounts
      ExcludeAccounts:
        default: Exclude AWS accounts
Parameters:
  NameSuffix:
    Type: String
    Description: Suffix to append to the resource name identifiers
    AllowedPattern: '[0-9a-z]+'
    MaxLength: 8
    MinLength: 4
  ExternalID:
    Type: String
    Description: Sysdig assigned token that proves you own this account
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  IsOrganizational:
    Type: String
    Description: Install into an organization
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  OrganizationalUnitIDs:
    Type: CommaDelimitedList
    Description: (Deprecated, use RootOUID or IncludeOUIDs instead) Comma separated list of organizational unit IDs to deploy
  Partition:
    Type: String
    Description: AWS Partition of your account or organization to create resources in
    Default: 'aws'
  RootOUID:
    Type: String
    Description: Root Organizational Unit ID of your AWS organization
  IncludeOUIDs:
    Type: CommaDelimitedList
    Description: Comma separated list of organizational unit IDs to be included for deployment
  ExcludeOUIDs:
    Type: CommaDelimitedList
    Description: Comma separated list of organizational unit IDs to be excluded for deployment
  IncludeAccounts:
    Type: CommaDelimitedList
    Description: Comma separated list of AWS accounts in your organization to be included for deployment
  ExcludeAccounts:
    Type: CommaDelimitedList
    Description: Comma separated list of AWS accounts in your organization to be excluded for deployment
Conditions:
  IsOrganizational:
    Fn::Equals:
    - Ref: IsOrganizational
    - 'true'
Resources:
  ConfigPostureRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sysdig-secure-posture-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Ref: TrustedIdentity
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
      ManagedPolicyArns:
      - !Sub arn:${Partition}:iam::aws:policy/SecurityAudit
      Policies:
      - PolicyName: !Sub sysdig-secure-posture-${NameSuffix}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: elasticfilesystem:DescribeAccessPoints
            Resource: '*'
          - Effect: Allow
            Action:
            - waf-regional:ListRules
            - waf-regional:ListRuleGroups
            Resource:
            - !Sub arn:${Partition}:waf-regional:*:*:rule/*
            - !Sub arn:${Partition}:waf-regional:*:*:rulegroup/*
          - Effect: Allow
            Action: macie2:ListClassificationJobs
            Resource: '*'
          - Effect: Allow
            Action:
            - lambda:GetRuntimeManagementConfig
            - lambda:GetFunction
            Resource: '*'
          - Effect: Allow
            Action: account:GetContactInformation
            Resource: '*'
  OnboardingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sysdig-secure-onboarding-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Ref: TrustedIdentity
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: ExternalID
      ManagedPolicyArns:
        Fn::If:
        - IsOrganizational
        - - !Sub arn:${Partition}:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - - !Ref AWS::NoValue
      Policies:
      - PolicyName: !Sub sysdig-secure-onboarding-${NameSuffix}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - account:Get*
            - account:List*
            Resource: '*'
  OrganizationStackSet:
    Type: AWS::CloudFormation::StackSet
    Condition: IsOrganizational
    Properties:
      StackSetName: !Sub sysdig-secure-organization-${NameSuffix}
      Description: Creates IAM roles within an AWS organization
      PermissionModel: SERVICE_MANAGED
      Capabilities:
      - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 90
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
      Parameters:
      - ParameterKey: NameSuffix
        ParameterValue:
          Ref: NameSuffix
      - ParameterKey: TrustedIdentity
        ParameterValue:
          Ref: TrustedIdentity
      - ParameterKey: ExternalID
        ParameterValue:
          Ref: ExternalID
      - ParameterKey: Partition
        ParameterValue:
          Ref: Partition
      StackInstancesGroup:
      - DeploymentTargets:
          OrganizationalUnitIds: !Ref OrganizationalUnitIDs
        Regions:
        - Ref: AWS::Region
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role for Agentless
        Parameters:
          NameSuffix:
            Type: String
            Description: Suffix to append to the resource name identifiers
            AllowedPattern: "[0-9a-z]+"
            MaxLength: 8
            MinLength: 4
          TrustedIdentity:
            Type: String
            Description: Trusted identity
          ExternalID:
            Type: String
            Description: external ID
          Partition:
            Type: String
            Description: AWS Partition of your account or organization to create resources in

        Resources:
          ConfigPostureRole:
            Type: "AWS::IAM::Role"
            Properties:
              RoleName: !Sub sysdig-secure-posture-${NameSuffix}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Effect: "Allow"
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Action: "sts:AssumeRole"
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
              ManagedPolicyArns:
              - !Sub arn:${Partition}:iam::aws:policy/SecurityAudit
              Policies:
              - PolicyName: !Sub sysdig-secure-posture-${NameSuffix}
                PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                  - Effect: "Allow"
                    Action: "elasticfilesystem:DescribeAccessPoints"
                    Resource: "*"
                  - Effect: "Allow"
                    Action:
                    - "waf-regional:ListRules"
                    - "waf-regional:ListRuleGroups"
                    Resource:
                    - !Sub arn:${Partition}:waf-regional:*:*:rule/*
                    - !Sub arn:${Partition}:waf-regional:*:*:rulegroup/*
                  - Effect: "Allow"
                    Action: "macie2:ListClassificationJobs"
                    Resource: "*"
                  - Effect: "Allow"
                    Action:
                    - "lambda:GetRuntimeManagementConfig"
                    - "lambda:GetFunction"
                    Resource: "*"
                  - Effect: "Allow"
                    Action: "account:GetContactInformation"
                    Resource: "*"
          OnboardingRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub sysdig-secure-onboarding-${NameSuffix}
              AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Action: sts:AssumeRole
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
              Policies:
              - PolicyName: !Sub sysdig-secure-onboarding-${NameSuffix}
                PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                  - Effect: Allow
                    Action:
                    - account:Get*
                    - account:List*
                    Resource: '*'

Outputs:
  ConfigPostureRoleARN:
    Description: ARN of the role for config posture
    Value:
      Fn::Sub: ${ConfigPostureRole.Arn}
  OnboardingRoleARN:
    Description: ARN of the onboarding role
    Value:
      Fn::Sub: ${OnboardingRole.Arn}
