AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: Sysdig Secure Agentless Workload Scanning Onboarding
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Sysdig Assigned Settings (Do not change)
        Parameters:
          - NameSuffix
          - ExternalID
          - TrustedIdentity
          - LambdaScanningEnabled
          - IsOrganizational
          - OrganizationalUnitIDs
          - RootOUID
          - IncludeOUIDs
          - ExcludeOUIDs
          - IncludeAccounts
          - ExcludeAccounts
    ParameterLabels:
      NameSuffix:
        default: Name Suffix
      ExternalID:
        default: External ID
      TrustedIdentity:
        default: Trusted Identity
      LambdaScanningEnabled:
        default: Enable Lambda Scanning
      IsOrganizational:
        default: Is Organizational Deployment?
      OrganizationalUnitIDs:
        default: (Deprecated, use RootOUID or IncludeOUIDs instead) Organizational Unit IDs
      RootOUID:
        default: Root Organization Unit ID
      IncludeOUIDs:
        default: Include Organizational Unit IDs
      ExcludeOUIDs:
        default: Exclude Organizational Unit IDs
      IncludeAccounts:
        default: Include AWS accounts
      ExcludeAccounts:
        default: Exclude AWS accounts
Parameters:
  NameSuffix:
    Type: String
    Description: Suffix to append to the resource name identifiers
    AllowedPattern: '[0-9a-z]+'
    MaxLength: 8
    MinLength: 4
  ExternalID:
    Type: String
    Description: Sysdig assigned token that proves you own this account
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  LambdaScanningEnabled:
    Type: String
    Description: Enable Lambda function scanning
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  IsOrganizational:
    Type: String
    Description: Whether this is an organizational deployment
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  OrganizationalUnitIDs:
    Type: CommaDelimitedList
    Description: (Deprecated, use RootOUID or IncludeOUIDs instead) Comma-separated list of organizational unit IDs to deploy (required for organizational deployments)
  RootOUID:
    Type: CommaDelimitedList
    Description: Root Organizational Unit ID of your AWS organization
  IncludeOUIDs:
    Type: CommaDelimitedList
    Description: Comma separated list of organizational unit IDs to be included for deployment
  ExcludeOUIDs:
    Type: CommaDelimitedList
    Description: Comma separated list of organizational unit IDs to be excluded for deployment
  IncludeAccounts:
    Type: CommaDelimitedList
    Description: Comma separated list of AWS accounts in your organization to be included for deployment
  ExcludeAccounts:
    Type: CommaDelimitedList
    Description: Comma separated list of AWS accounts in your organization to be excluded for deployment

Conditions:
  IsOrganizational:
    Fn::Equals:
      - Ref: IsOrganizational
      - 'true'
  IsLambdaEnabled:
    Fn::Equals:
      - Ref: LambdaScanningEnabled
      - 'true'
  OUInclusionsConfigured:
    !And
    - !Condition IsOrganizational
    - !Not
      - !Equals
        - Fn::Length:
          - !Ref IncludeOUIDs
        - 0
  AccountInclusionsConfigured:
    !And
    - !Condition IsOrganizational
    - !Not
      - !Equals
        - Fn::Length:
          - !Ref IncludeAccounts
        - 0
  # -----------------------------------------------------------------------------------------------------
  # Remove below condition once AWS issue is fixed and replace with using UNION filter -
  # https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/issues/100
  # -----------------------------------------------------------------------------------------------------
  # XXX: due to AWS bug of not having UNION filter fully working, there is no way to add those extra accounts requested.
  # to not miss out on those extra accounts, deploy the cloud resources across entire org and noop the UNION filter.
  # i.e till we can't deploy UNION, we deploy it all ()
  AllowedInclusions:
    !And
    - !Condition OUInclusionsConfigured
    - !Not
      - !Condition AccountInclusionsConfigured

  # cannot do OU exclusions since CFT templates are static and don't have a way to fetch dynamic data from AWS
  AccountExclusionsConfigured:
    !And
    - !Condition IsOrganizational
    - !Equals
      - Fn::Length:
        - !Ref IncludeAccounts
      - 0
    - !Not
      - !Equals
        - Fn::Length:
          - !Ref ExcludeAccounts
        - 0

Resources:
  ScanningRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sysdig-vm-workload-scanning-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Ref: TrustedIdentity
            Action: ['sts:AssumeRole']
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalID
  ECRPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-ecr
      Roles:
        - !Ref ScanningRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:ListImages
              - ecr:GetAuthorizationToken
            Resource: '*'
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Condition: IsLambdaEnabled
    Properties:
      PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-lambda
      Roles:
        - !Ref ScanningRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:GetFunction
              - lambda:GetFunctionConfiguration
              - lambda:GetRuntimeManagementConfig
              - lambda:ListFunctions
              #- lambda:ListTagsForResource
              #- lambda:GetLayerVersionByArn
              - lambda:GetLayerVersion
              - lambda:ListLayers
              - lambda:ListLayerVersions
            Resource: '*'


  ScanningOrgStackSet:
    Type: AWS::CloudFormation::StackSet
    Condition: IsOrganizational
    Properties:
      StackSetName: !Sub sysdig-vm-workload-scanning-${NameSuffix}
      Description: Creates IAM roles within an AWS organization for Agentless Workload Scanning
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 90
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
      Parameters:
        - ParameterKey: NameSuffix
          ParameterValue:
            Ref: NameSuffix
        - ParameterKey: TrustedIdentity
          ParameterValue:
            Ref: TrustedIdentity
        - ParameterKey: ExternalID
          ParameterValue:
            Ref: ExternalID
        - ParameterKey: LambdaScanningEnabled
          ParameterValue:
            Ref: LambdaScanningEnabled
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              Fn::If:
              - AllowedInclusions
              - !Ref IncludeOUIDs
              - !Ref RootOUID
            AccountFilterType:
              Fn::If:
              - AccountExclusionsConfigured
              - "DIFFERENCE"
              - "NONE"
            Accounts:
              Fn::If:
              - AccountExclusionsConfigured
              - !Ref ExcludeAccounts
              - null
          Regions:
            - Ref: AWS::Region
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role for Agentless Workload Scanning
        Parameters:
          NameSuffix:
            Type: String
            Description: Suffix to append to the resource name identifiers
            AllowedPattern: "[0-9a-z]+"
            MaxLength: 8
            MinLength: 4
          TrustedIdentity:
            Type: String
            Description: Trusted identity
          ExternalID:
            Type: String
            Description: external ID
          LambdaScanningEnabled:
            Type: String
            Description: Enable Lambda function scanning
            Default: 'false'
        Conditions:
          IsLambdaEnabled:
            Fn::Equals:
              - Ref: LambdaScanningEnabled
              - 'true'
        Resources:
          ScanningRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub sysdig-vm-workload-scanning-${NameSuffix}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Effect: "Allow"
                  Action: "sts:AssumeRole"
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
          ECRPolicy:
            Type: AWS::IAM::Policy
            Properties:
              PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-ecr
              Roles:
                - !Ref ScanningRole
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - ecr:GetDownloadUrlForLayer
                      - ecr:BatchGetImage
                      - ecr:BatchCheckLayerAvailability
                      - ecr:ListImages
                      - ecr:GetAuthorizationToken
                    Resource: '*'
          LambdaPolicy:
            Type: AWS::IAM::Policy
            Condition: IsLambdaEnabled
            Properties:
              PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-lambda
              Roles:
                - !Ref ScanningRole
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - lambda:GetFunction
                      - lambda:GetFunctionConfiguration
                      - lambda:GetRuntimeManagementConfig
                      - lambda:ListFunctions
                      - lambda:GetLayerVersion
                      - lambda:ListLayers
                      - lambda:ListLayerVersions
                    Resource: '*'
                


Outputs:
  ScanningRoleARN:
    Description: ARN of the scanning role
    Value:
      Fn::Sub: sysdig-vm-workload-scanning-${NameSuffix}

