AWSTemplateFormatVersion: '2010-09-09'
Description: Sysdig Secure Agentless Workload Scanning Onboarding
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Sysdig Assigned Settings (Do not change)
        Parameters:
          - NameSuffix
          - ExternalID
          - TrustedIdentity
          - LambdaScanningEnabled
          - IsOrganizational
          - OrganizationalUnitIDs
    ParameterLabels:
      NameSuffix:
        default: Name Suffix
      ExternalID:
        default: External ID
      TrustedIdentity:
        default: Trusted Identity
      LambdaScanningEnabled:
        default: Enable Lambda Scanning
      IsOrganizational:
        default: Is Organizational Deployment?
      OrganizationalUnitIDs:
        default: Organizational Unit IDs
Parameters:
  NameSuffix:
    Type: String
    Description: Suffix to append to the resource name identifiers
    AllowedPattern: '[0-9a-z]+'
    MaxLength: 8
    MinLength: 4
  ExternalID:
    Type: String
    Description: Sysdig assigned token that proves you own this account
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  LambdaScanningEnabled:
    Type: String
    Description: Enable Lambda function scanning
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  IsOrganizational:
    Type: String
    Description: Whether this is an organizational deployment
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  OrganizationalUnitIDs:
    Type: CommaDelimitedList
    Description: Comma-separated list of organizational unit IDs to deploy (required for organizational deployments)

Conditions:
  IsOrganizational:
    Fn::Equals:
      - Ref: IsOrganizational
      - 'true'
  IsNotOrganizational:
    Fn::Equals:
      - Ref: IsOrganizational
      - 'false'
  IsNotOrganizationalAndLambdaEnabled:
    Fn::And:
      - Fn::Equals:
        - Ref: IsOrganizational
        - 'false'
      - Fn::Equals:
        - Ref: LambdaScanningEnabled
        - 'true'

Resources:
  ScanningRole:
    Type: AWS::IAM::Role
    Condition: IsNotOrganizational
    Properties:
      RoleName: !Sub sysdig-vm-workload-scanning-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Ref: TrustedIdentity
            Action: ['sts:AssumeRole']
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalID
  ECRPolicy:
    Type: AWS::IAM::Policy
    Condition: IsNotOrganizational
    Properties:
      PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-ecr
      Roles:
        - !Ref ScanningRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:ListImages
              - ecr:GetAuthorizationToken
            Resource: '*'
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Condition: IsNotOrganizationalAndLambdaEnabled
    Properties:
      PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-lambda
      Roles:
        - !Ref ScanningRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:GetFunction
              - lambda:GetFunctionConfiguration
              - lambda:GetRuntimeManagementConfig
              - lambda:ListFunctions
              - lambda:ListTagsForResource
              - lambda:GetLayerVersionByArn
              - lambda:GetLayerVersion
              - lambda:ListLayers
              - lambda:ListLayerVersions
            Resource: '*'


  ScanningOrgStackSet:
    Type: AWS::CloudFormation::StackSet
    Condition: IsOrganizational
    Properties:
      StackSetName: !Sub sysdig-vm-workload-scanning-${NameSuffix}
      Description: Creates IAM roles within an AWS organization for Agentless Workload Scanning
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 90
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
      Parameters:
        - ParameterKey: NameSuffix
          ParameterValue:
            Ref: NameSuffix
        - ParameterKey: TrustedIdentity
          ParameterValue:
            Ref: TrustedIdentity
        - ParameterKey: ExternalID
          ParameterValue:
            Ref: ExternalID
        - ParameterKey: LambdaScanningEnabled
          ParameterValue:
            Ref: LambdaScanningEnabled
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref OrganizationalUnitIDs
          Regions:
            - Ref: AWS::Region
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role for Agentless Workload Scanning
        Parameters:
          NameSuffix:
            Type: String
            Description: Suffix to append to the resource name identifiers
            AllowedPattern: "[0-9a-z]+"
            MaxLength: 8
            MinLength: 4
          TrustedIdentity:
            Type: String
            Description: Trusted identity
          ExternalID:
            Type: String
            Description: external ID
          LambdaScanningEnabled:
            Type: String
            Description: Enable Lambda function scanning
            Default: 'false'
        Conditions:
          IsLambdaEnabled:
            Fn::Equals:
              - Ref: LambdaScanningEnabled
              - 'true'
        Resources:
          ScanningRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub sysdig-vm-workload-scanning-${NameSuffix}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Effect: "Allow"
                  Action: "sts:AssumeRole"
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
          ECRPolicy:
            Type: AWS::IAM::Policy
            Properties:
              PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-ecr
              Roles:
                - !Ref ScanningRole
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - ecr:GetDownloadUrlForLayer
                      - ecr:BatchGetImage
                      - ecr:BatchCheckLayerAvailability
                      - ecr:ListImages
                      - ecr:GetAuthorizationToken
                    Resource: '*'
          LambdaPolicy:
            Type: AWS::IAM::Policy
            Condition: LambdaScanningEnabled
            Properties:
              PolicyName: !Sub sysdig-vm-workload-scanning-${NameSuffix}-lambda
              Roles:
                - !Ref ScanningRole
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - lambda:GetFunction
                      - lambda:GetFunctionConfiguration
                      - lambda:GetRuntimeManagementConfig
                      - lambda:ListFunctions
                      - lambda:ListTagsForResource
                      - lambda:GetLayerVersionByArn
                      - lambda:GetLayerVersion
                      - lambda:ListLayers
                      - lambda:ListLayerVersions
                    Resource: '*'
                


Outputs:
  ScanningRoleARN:
    Description: ARN of the scanning role
    Value:
      Fn::Sub: sysdig-vm-workload-scanning-${NameSuffix}

