AWSTemplateFormatVersion: '2010-09-09'
Description: Sysdig Agentless Scanning integration resources
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "Sysdig Settings (Do not change)"
      Parameters:
      - NameSuffix
      - ExternalID
      - TrustedIdentity
      - ScanningAccountID
      - Regions
      - IsOrganizational
      - OrganizationalUnitIDs
    ParameterLabels:  
      NameSuffix:
        default: Name Suffix
      ExternalID:
        default: "External ID"
      TrustedIdentity:
        default: "Trusted Identity"
      ScanningAccountID:
        default: "Sysdig Scanning Account ID"
      Regions:
        default: "Instrumented Regions"
      IsOrganizational:
        default: Is Organizational
      OrganizationalUnitIDs:
        default: "Organizational Unit IDs"

Parameters:
  NameSuffix:
    Type: String
    Description: Suffix to append to the resource name identifiers
    AllowedPattern: '[0-9a-z]+'
    MaxLength: 8
    MinLength: 4
  ExternalID:
    Type: String
    Description: Sysdig assigned token that proves you own this account
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  ScanningAccountID:
    Type: String
    Description: The AWS Account ID of the Sysdig Scanning Account
    Default: '878070807337'
  Regions:
    Type: CommaDelimitedList
    Description: Comma separated list of regions enabled for Sysdig Scanning
  IsOrganizational:
    Type: String
    Description: Install into an organization
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  OrganizationalUnitIDs:
    Type: CommaDelimitedList
    Description: Comma separated list of organizational unit IDs to deploy

Conditions:
  IsOrganizational:
    Fn::Equals:
    - Ref: IsOrganizational
    - 'true'

Resources:        
  AdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub sysdig-secure-scanning-stackset-administration-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: !Sub sysdig-secure-scanning-stackset-execution-${NameSuffix}
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - sts:AssumeRole
            Resource:
            - !Sub arn:aws:iam:::role/sysdig-secure-scanning-stackset-execution-${NameSuffix}
  ExecutionRole:
    Type: AWS::IAM::Role   
    Properties:
      RoleName: !Sub sysdig-secure-scanning-stackset-execution-${NameSuffix}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - !GetAtt AdministrationRole.RoleId
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      - arn:aws:iam::aws:policy/IAMFullAccess
  AccountStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Sub sysdig-secure-scanning-account-${NameSuffix}
      Description: "Creates a KMS key with an associated IAM role, unique per region within the target account"
      AdministrationRoleARN: !GetAtt AdministrationRole.Arn
      ExecutionRoleName: !Ref ExecutionRole
      PermissionModel: SELF_MANAGED
      ManagedExecution:
        Active: true      
      Capabilities:
        - CAPABILITY_NAMED_IAM 
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 90
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        RegionConcurrencyType: PARALLEL
      Parameters:
      - ParameterKey: NameSuffix
        ParameterValue: !Ref NameSuffix
      - ParameterKey: ScanningAccountID
        ParameterValue: !Ref ScanningAccountID
      - ParameterKey: TrustedIdentity
        ParameterValue: !Ref TrustedIdentity
      - ParameterKey: ExternalID
        ParameterValue: !Ref ExternalID
      StackInstancesGroup:
      - DeploymentTargets:
          Accounts: 
          - !Ref AWS::AccountId
        Regions: !Ref Regions
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: "Template to create KMS Key and Alias for Sysdig Agentless Scanning"
        Parameters: 
          NameSuffix:
            Type: String
            Description: Suffix to append to the resource name identifiers
            AllowedPattern: '[0-9a-z]+'
            MaxLength: 8
            MinLength: 4
          ScanningAccountID:
            Type: String
            Description: The AWS Account ID of the Sysdig Scanning Account  
          TrustedIdentity:
            Type: String
            Description: The Role in Sysdig's AWS Account with permissions to your account
          ExternalID:
            Type: String
            Description: Sysdig assigned token that proves you own this account
        Resources:
          ScanningRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub sysdig-secure-scanning-${NameSuffix}-${AWS::Region}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Effect: "Allow"
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Action: "sts:AssumeRole"
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
              Policies:
              - PolicyName: !Sub sysdig-secure-scanning-${NameSuffix}
                PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                  - Sid: "Read"
                    Effect: "Allow"
                    Action: 
                    - "ec2:Describe*"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "AllowKMSKeysListing"
                    Effect: "Allow"
                    Action:
                    - "kms:ListKeys"
                    - "kms:ListAliases"
                    - "kms:ListResourceTags"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "AllowKMSEncryptDecrypt"
                    Effect: "Allow"
                    Action:
                    - "kms:DescribeKey"
                    - "kms:Encrypt"
                    - "kms:Decrypt"
                    - "kms:ReEncrypt*"
                    - "kms:GenerateDataKey*"
                    - "kms:CreateGrant"
                    Resource: "*"
                    Condition:
                      StringLike:
                        "kms:ViaService": "ec2.*.amazonaws.com"
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "CreateTaggedSnapshotFromVolume"
                    Effect: "Allow"
                    Action:
                    - "ec2:CreateSnapshot"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "CopySnapshots"
                    Effect: "Allow"
                    Action:
                    - "ec2:CopySnapshot"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "SnapshotTags"
                    Effect: "Allow"
                    Action:
                    - "ec2:CreateTags"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "ec2:CreateAction": ["CreateSnapshot", "CopySnapshot"]
                        "aws:RequestTag/CreatedBy": "Sysdig"
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "ec2SnapshotShare"
                    Effect: "Allow"
                    Action:
                    - "ec2:ModifySnapshotAttribute"
                    Resource: "*"
                    Condition:
                      StringEqualsIgnoreCase:
                        "aws:ResourceTag/CreatedBy": "Sysdig"
                      StringEquals:
                        "ec2:Add/userId": !Ref ScanningAccountID
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "ec2SnapshotDelete"
                    Effect: "Allow"
                    Action:
                    - "ec2:DeleteSnapshot"
                    Resource: "*"
                    Condition:
                      StringEqualsIgnoreCase:
                        "aws:ResourceTag/CreatedBy": "Sysdig"
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
          ScanningKmsKey:
            Type: 'AWS::KMS::Key'
            Properties:
              Description: "Sysdig Agentless Scanning encryption key"
              PendingWindowInDays: 7
              KeyUsage: ENCRYPT_DECRYPT
              EnableKeyRotation: true   # Enables automatic yearly rotation
              KeyPolicy:
                Version: '2012-10-17'
                Statement:
                - Sid: "SysdigAllowKms"
                  Effect: "Allow"
                  Principal:
                    AWS:
                    - !Sub arn:aws:iam::${ScanningAccountID}:root
                    - !GetAtt ScanningRole.Arn
                  Action:
                  - "kms:Encrypt"
                  - "kms:Decrypt"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                  - "kms:DescribeKey"
                  - "kms:CreateGrant"
                  - "kms:ListGrants"
                  Resource: "*"
                - Sid: "AllowCustomerManagement"
                  Effect: "Allow"
                  Principal:
                    AWS:
                    - !Sub arn:aws:iam::${AWS::AccountId}:root
                    - !Sub arn:aws:iam::${AWS::AccountId}:role/sysdig-secure-scanning-stackset-execution-${NameSuffix}
                  Action: "kms:*"
                  Resource: "*"
          ScanningKmsAlias:
            Type: 'AWS::KMS::Alias'
            Properties:
              AliasName: !Sub alias/sysdig-secure-scanning-${NameSuffix}
              TargetKeyId: !Ref ScanningKmsKey
  OrganizationStackSet:
    Type: AWS::CloudFormation::StackSet
    Condition: IsOrganizational
    Properties:
      StackSetName: !Sub sysdig-secure-scanning-organization-${NameSuffix}
      Description: Installs KMS key, alias, and IAM role for use with Sysdig Agentless Scanning
      PermissionModel: SERVICE_MANAGED
      Capabilities:
      - "CAPABILITY_NAMED_IAM"
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false         
      ManagedExecution:
        Active: true        
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 90
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        RegionConcurrencyType: PARALLEL
      Parameters:
      - ParameterKey: NameSuffix
        ParameterValue: !Ref NameSuffix
      - ParameterKey: ScanningAccountID
        ParameterValue: !Ref ScanningAccountID
      - ParameterKey: TrustedIdentity
        ParameterValue: !Ref TrustedIdentity
      - ParameterKey: ExternalID
        ParameterValue: !Ref ExternalID
      StackInstancesGroup:
      - DeploymentTargets:
          OrganizationalUnitIds: !Ref OrganizationalUnitIDs
        Regions: !Ref Regions
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role used by Sysdig Secure Vulnerability Scanning
        Parameters:
          NameSuffix:
            Type: String
            Description: Suffix to append to the resource name identifiers
            AllowedPattern: '[0-9a-z]+'
            MaxLength: 8
            MinLength: 4
          ExternalID:
            Type: String
            Description: Sysdig assigned token that proves you own this account
          TrustedIdentity:
            Type: String
            Description: The Role in Sysdig's AWS Account with permissions to your account
          ScanningAccountID:
            Type: String
            Description: The AWS Account ID of the Sysdig Scanning Account
        Resources:
          ScanningRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub sysdig-secure-scanning-${NameSuffix}-${AWS::Region}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Effect: "Allow"
                  Principal:
                    AWS: !Ref TrustedIdentity
                  Action: "sts:AssumeRole"
                  Condition:
                    StringEquals:
                      sts:ExternalId: !Ref ExternalID
              Policies:
              - PolicyName: !Sub sysdig-secure-scanning-${NameSuffix}
                PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                  - Sid: "Read"
                    Effect: "Allow"
                    Action: 
                    - "ec2:Describe*"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "AllowKMSKeysListing"
                    Effect: "Allow"
                    Action:
                    - "kms:ListKeys"
                    - "kms:ListAliases"
                    - "kms:ListResourceTags"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "AllowKMSEncryptDecrypt"
                    Effect: "Allow"
                    Action:
                    - "kms:DescribeKey"
                    - "kms:Encrypt"
                    - "kms:Decrypt"
                    - "kms:ReEncrypt*"
                    - "kms:GenerateDataKey*"
                    - "kms:CreateGrant"
                    Resource: "*"
                    Condition:
                      StringLike:
                        "kms:ViaService": "ec2.*.amazonaws.com"
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "CreateTaggedSnapshotFromVolume"
                    Effect: "Allow"
                    Action:
                    - "ec2:CreateSnapshot"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "CopySnapshots"
                    Effect: "Allow"
                    Action:
                    - "ec2:CopySnapshot"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "SnapshotTags"
                    Effect: "Allow"
                    Action:
                    - "ec2:CreateTags"
                    Resource: "*"
                    Condition:
                      StringEquals:
                        "ec2:CreateAction": ["CreateSnapshot", "CopySnapshot"]
                        "aws:RequestTag/CreatedBy": "Sysdig"
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "ec2SnapshotShare"
                    Effect: "Allow"
                    Action:
                    - "ec2:ModifySnapshotAttribute"
                    Resource: "*"
                    Condition:
                      StringEqualsIgnoreCase:
                        "aws:ResourceTag/CreatedBy": "Sysdig"
                      StringEquals:
                        "ec2:Add/userId": !Ref ScanningAccountID
                        "aws:RequestedRegion": !Ref AWS::Region
                  - Sid: "ec2SnapshotDelete"
                    Effect: "Allow"
                    Action:
                    - "ec2:DeleteSnapshot"
                    Resource: "*"
                    Condition:
                      StringEqualsIgnoreCase:
                        "aws:ResourceTag/CreatedBy": "Sysdig" 
                      StringEquals:
                        "aws:RequestedRegion": !Ref AWS::Region
          ScanningKmsKey:
            Type: 'AWS::KMS::Key'
            Properties:
              Description: "Sysdig Agentless Scanning encryption key"
              PendingWindowInDays: 7
              KeyUsage: ENCRYPT_DECRYPT
              EnableKeyRotation: true   # Enables automatic yearly rotation
              KeyPolicy:
                Version: '2012-10-17'
                Statement:
                - Sid: "SysdigAllowKms"
                  Effect: "Allow"
                  Principal:
                    AWS:
                    - !Sub arn:aws:iam::${ScanningAccountID}:root
                    - !GetAtt ScanningRole.Arn
                  Action:
                  - "kms:Encrypt"
                  - "kms:Decrypt"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                  - "kms:DescribeKey"
                  - "kms:CreateGrant"
                  - "kms:ListGrants"
                  Resource: "*"
                - Sid: "AllowCustomerManagement"
                  Effect: "Allow"
                  Principal:
                    AWS:
                    - !Sub arn:aws:iam::${AWS::AccountId}:root
                    - !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/member.org.stacksets.cloudformation.amazonaws.com/AWSServiceRoleForCloudFormationStackSetsOrgMember
                  Action: "kms:*"
                  Resource: "*"
          ScanningKmsAlias:
            Type: 'AWS::KMS::Alias'
            Properties:
              AliasName: !Sub alias/sysdig-secure-scanning-${NameSuffix}
              TargetKeyId: !Ref ScanningKmsKey