repos:
 - repo: local
    hooks:
    -   id: format
        pass_filenames: false
        name: lint
        entry: make -C templates_apprunner lint && make -C templates_ecs lint
        language: system
