AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role and EventBridge resources used by Sysdig Secure
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - CSPMRoleName
          - EventBridgeRoleName
          - ExternalID
          - TrustedIdentity
          - EventBusARN
          - Regions
          - OrganizationUnitIDs
          - EventBridgeState
    ParameterLabels:
      CSPMRoleName:
        default: "CSPM Role Name (Sysdig use only)"
      EventBridgeRoleName:
        default: "Integration Name (Sysdig use only)"        
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"
      EventBusARN:
        default: "Target Event Bus (Sysdig use only)"
      Regions:
        default: "EventBridge Regions (Sysdig use only)"
      OrganizationUnitIDs:
        default: "Organization Unit IDs (Sysdig use only)"
      EventBridgeState:
        default: "State of the EventBridge Rule (Sysdig use only)"  
Parameters:
  CSPMRoleName:
    Type: String
    Description: The read-only IAM Role that Sysdig will create
  EventBridgeRoleName:
    Type: String
    Description: A unique identifier used to create an IAM Role and EventBridge Rule
  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  EventBusARN:
    Type: String
    Description: The destination in Sysdig's AWS account where your events are sent
  Regions:
    Type: String
    Description: Comma separated list of regions to monitor with EventBridge    
  OrganizationUnitIDs:
    Type: String
    Description: Organization Unit IDs to deploy
  EventBridgeState:
    Type: String
    Description: The state of the EventBridge Rule
    Default: ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
    AllowedValues:
      - ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
      - ENABLED
      - DISABLED
       
Resources:
  AdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - "arn:*:iam::*:role/AWSCloudFormationStackSetExecutionRole"
  ExecutionRole:
    Type: AWS::IAM::Role   
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt AdministrationRole.RoleId
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  CloudAgentlessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${CSPMRoleName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub ${TrustedIdentity}
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${ExternalID}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Policies:
        - PolicyName: !Sub ${CSPMRoleName}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "elasticfilesystem:DescribeAccessPoints"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "waf-regional:ListRules"
                  - "waf-regional:ListRuleGroups"
                Resource:
                  - "arn:aws:waf-regional:*:*:rule/*"
                  - "arn:aws:waf-regional:*:*:rulegroup/*"
              - Effect: "Allow"
                Action: "macie2:ListClassificationJobs"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "lambda:GetRuntimeManagementConfig"
                  - "lambda:GetFunction"
                Resource: "*"
              - Effect: "Allow"
                Action: "account:GetContactInformation"
                Resource: "*"
              - Effect: "Allow"
                Action: "bedrock:ListAgents"
                Resource: "*"
              - Effect: "Allow"
                Action: "bedrock:ListCustomModels"
                Resource: "*"
              - Effect: "Allow"
                Action: "bedrock:ListKnowledgeBases"
                Resource: "*"
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EventBridgeRoleName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
          - Effect: "Allow"
            Principal:
              AWS: !Sub ${TrustedIdentity}
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${ExternalID}
      Policies:
        - PolicyName: !Sub ${EventBridgeRoleName}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'events:PutEvents'
                Resource: !Sub ${EventBusARN}
              - Effect: Allow
                Action:
                  - "events:DescribeRule"
                  - "events:ListTargetsByRule"
                Resource:
                  - !Sub arn:aws:events:*:*:rule/${EventBridgeRoleName}
  RolesStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: RolesStackSet
      Description: IAM Role used to forward CloudTrail logs to Sysdig Secure
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - "CAPABILITY_NAMED_IAM"
      AutoDeployment:
        Enabled: false
      OperationPreferences:
        MaxConcurrentCount: 5
      Parameters:
        - ParameterKey: CSPMRoleName
          ParameterValue: !Ref CSPMRoleName
        - ParameterKey: TrustedIdentity
          ParameterValue: !Ref TrustedIdentity
        - ParameterKey: ExternalID
          ParameterValue: !Ref ExternalID
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
        - ParameterKey: EventBusARN
          ParameterValue: !Ref EventBusARN
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Split [ ",", !Ref OrganizationUnitIDs]
          Regions: [!Ref "AWS::Region"]
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role used to forward CloudTrail logs to Sysdig Secure
        Parameters:
          CSPMRoleName:
            Type: String
            Description: A unique identifier used to create an IAM Role and EventBridge Rule        
          TrustedIdentity:
            Type: String
            Description: The Role in Sysdig's AWS Account with permissions to your account
          ExternalID:
            Type: String
            Description: Sysdig ExternalID required for the policy creation
          EventBridgeRoleName:
            Type: String
            Description: A unique identifier used to create an IAM Role and EventBridge Rule
          EventBusARN:
            Type: String
            Description: The destination in Sysdig's AWS account where your events are sent                       
        Resources:
          CloudAgentlessRole:
            Type: "AWS::IAM::Role"
            Properties:
              RoleName: !Sub ${CSPMRoleName}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: "Allow"
                    Principal:
                      AWS: !Sub ${TrustedIdentity}
                    Action: "sts:AssumeRole"
                    Condition:
                      StringEquals:
                        sts:ExternalId: !Sub ${ExternalID}
              ManagedPolicyArns:
                - arn:aws:iam::aws:policy/SecurityAudit
              Policies:
                - PolicyName: !Sub ${CSPMRoleName}
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Effect: "Allow"
                        Action: "elasticfilesystem:DescribeAccessPoints"
                        Resource: "*"
                      - Effect: "Allow"
                        Action:
                          - "waf-regional:ListRules"
                          - "waf-regional:ListRuleGroups"
                        Resource:
                          - "arn:aws:waf-regional:*:*:rule/*"
                          - "arn:aws:waf-regional:*:*:rulegroup/*"
                      - Effect: "Allow"
                        Action: "macie2:ListClassificationJobs"
                        Resource: "*"
                      - Effect: "Allow"
                        Action:
                          - "lambda:GetRuntimeManagementConfig"
                          - "lambda:GetFunction"
                        Resource: "*"
                      - Effect: "Allow"
                        Action: "account:GetContactInformation"
                        Resource: "*"
                      - Effect: "Allow"
                        Action: "bedrock:ListAgents"
                        Resource: "*"
                      - Effect: "Allow"
                        Action: "bedrock:ListCustomModels"
                        Resource: "*"
                      - Effect: "Allow"
                        Action: "bedrock:ListKnowledgeBases"
                        Resource: "*"
          EventBridgeRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub ${EventBridgeRoleName}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Principal:
                      Service: events.amazonaws.com
                    Action: 'sts:AssumeRole'
                  - Effect: "Allow"
                    Principal:
                      AWS: !Sub ${TrustedIdentity}
                    Action: "sts:AssumeRole"
                    Condition:
                      StringEquals:
                        sts:ExternalId: !Sub ${ExternalID}          
              Policies:
                - PolicyName: !Sub ${EventBridgeRoleName}
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Effect: Allow
                        Action: 'events:PutEvents'
                        Resource: !Sub ${EventBusARN}
                      - Effect: Allow
                        Action:
                          - "events:DescribeRule"
                          - "events:ListTargetsByRule"
                        Resource:
                          - !Sub arn:aws:events:*:*:rule/${EventBridgeRoleName}
  EBRuleStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: EBRuleStackSet
      Description: EventBridge Resources that forward CloudTrail logs to Sysdig Secure
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - "CAPABILITY_NAMED_IAM"
      AutoDeployment:
        Enabled: false
      OperationPreferences:
        MaxConcurrentCount: 5
      Parameters:
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
        - ParameterKey: EventBusARN
          ParameterValue: !Ref EventBusARN
        - ParameterKey: EventBridgeState
          ParameterValue: !Ref EventBridgeState
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Split [ ",", !Ref OrganizationUnitIDs]
          Regions: !Split [ ",", !Ref Regions]
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: EventBridge Resources that forward CloudTrail logs to Sysdig Secure
        Parameters:
          EventBridgeRoleName:
            Type: String
            Description: A unique identifier used to create an IAM Role and EventBridge Rule
          EventBusARN:
            Type: String
            Description: The destination in Sysdig's AWS account where your events are sent 
          EventBridgeState:
            Type: String
            Description: The state of the EventBridge Rule
            Default: ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
            AllowedValues:
              - ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
              - ENABLED
              - DISABLED                        
        Resources:           
          EventBridgeRule:
            Type: "AWS::Events::Rule"
            Properties:
              Name: !Sub ${EventBridgeRoleName}
              Description: Capture all CloudTrail events
              EventPattern:
                detail-type:
                  - 'AWS API Call via CloudTrail'
                  - 'AWS Console Sign In via CloudTrail'
                  - 'AWS Service Event via CloudTrail'
                  - 'Object Access Tier Changed'
                  - 'Object ACL Updated'
                  - 'Object Created'
                  - 'Object Deleted'
                  - 'Object Restore Completed'
                  - 'Object Restore Expired'
                  - 'Object Restore Initiated'
                  - 'Object Storage Class Changed'
                  - 'Object Tags Added'
                  - 'Object Tags Deleted'
              State: !Sub ${EventBridgeState}
              Targets:
                - Id: !Sub ${EventBridgeRoleName}
                  Arn: !Sub ${EventBusARN}
                  RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${EventBridgeRoleName}"
  MgmtAccEBRuleStackSet:
    Type: AWS::CloudFormation::StackSet
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3005
    DependsOn: 
      - ExecutionRole
      - AdministrationRole
    Properties:
      StackSetName: MgmtAccEBRuleStackSet
      AdministrationRoleARN: !GetAtt AdministrationRole.Arn
      Description: EventBridge Resources that forward CloudTrail logs to Sysdig Secure
      PermissionModel: SELF_MANAGED
      Capabilities:
        - CAPABILITY_NAMED_IAM
      OperationPreferences:
        MaxConcurrentCount: 5
      Parameters:
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
        - ParameterKey: EventBusARN
          ParameterValue: !Ref EventBusARN
        - ParameterKey: EventBridgeState
          ParameterValue: !Ref EventBridgeState
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref AWS::AccountId
          Regions: !Split [ ",", !Ref Regions]
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: EventBridge Resources that forward CloudTrail logs to Sysdig Secure
        Parameters:
          EventBridgeRoleName:
            Type: String
            Description: A unique identifier used to create an IAM Role and EventBridge Rule
          EventBusARN:
            Type: String
            Description: The destination in Sysdig's AWS account where your events are sent
          EventBridgeState:
            Type: String
            Description: The state of the EventBridge Rule
            Default: ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
            AllowedValues:
              - ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS
              - ENABLED
              - DISABLED                     
        Resources:           
          EventBridgeRule:
            Type: "AWS::Events::Rule"
            Properties:
              Name: !Sub ${EventBridgeRoleName}
              Description: Capture all CloudTrail events
              EventPattern:
                detail-type:
                  - 'AWS API Call via CloudTrail'
                  - 'AWS Console Sign In via CloudTrail'
                  - 'AWS Service Event via CloudTrail'
                  - 'Object Access Tier Changed'
                  - 'Object ACL Updated'
                  - 'Object Created'
                  - 'Object Deleted'
                  - 'Object Restore Completed'
                  - 'Object Restore Expired'
                  - 'Object Restore Initiated'
                  - 'Object Storage Class Changed'
                  - 'Object Tags Added'
                  - 'Object Tags Deleted'
              State: !Sub ${EventBridgeState}
              Targets:
                - Id: !Sub ${EventBridgeRoleName}
                  Arn: !Sub ${EventBusARN}
                  RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${EventBridgeRoleName}"