AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template for provisioning the necessary resources for the
  `cloud-logs` component. This includes IAM roles, policies, and optional SNS
  topic and subscription for CloudTrail notifications.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - CloudLogsRoleName
          - ExternalID
          - TrustedIdentity
          - BucketARN
          - CreateTopic
          - TopicARN
          - Endpoint

    ParameterLabels:
      CloudLogsRoleName:
        default: "Role Name (Sysdig use only)"
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"
      BucketARN:
        default: "Bucket ARN"
      CreateTopic:
        default: "Create SNS Topic"
      TopicARN:
        default: "SNS Topic ARN"
      Endpoint:
        default: "Sysdig Secure endpoint"

Parameters:
  CloudLogsRoleName:
    Type: String
    Description: The name of the IAM Role that will enable access to the CloudTrail logs.

  ExternalID:
    Type: String
    Description: Random string generated unique to a customer.

  TrustedIdentity:
    Type: String
    Description: The name of Sysdig's trusted identity.

  BucketARN:
    Type: String
    Description: The ARN of your S3 bucket associated with your CloudTrail trail.

  CreateTopic:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description: "Whether to create a new SNS Topic for CloudTrail notifications."

  TopicARN:
    Type: String
    Default: ""
    Description: "The ARN of an existing SNS Topic. Ignored if CreateTopic is set to true."

  Endpoint:
    Type: String
    Default: ""
    Description: "Sysdig Secure endpoint to receive CloudTrail notifications."

Resources:
  # IAM Role
  CloudLogsRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref CloudLogsRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Ref TrustedIdentity
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref ExternalID

  # IAM Policy
  CloudLogsRolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "CloudlogsS3Access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "CloudlogsS3AccessGet"
            Effect: "Allow"
            Action:
              - "s3:Get*"
            Resource:
              - !Sub '${BucketARN}'
              - !Sub '${BucketARN}/*'
          - Sid: "CloudlogsS3AccessList"
            Effect: "Allow"
            Action:
              - "s3:List*"
            Resource:
              - !Sub '${BucketARN}'
              - !Sub '${BucketARN}/*'
      Roles:
        - !Ref CloudLogsRole

  # SNS Topic (optional creation)
  CloudTrailNotificationsTopic:
    Condition: CreateSNSTopic
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "${AWS::StackName}-CloudTrailNotifications"
      DisplayName: "CloudTrail Notifications for Sysdig"

  CloudTrailNotificationsSubscription:
    Condition: CreateSNSTopic
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref CloudTrailNotificationsTopic
      Protocol: "https"
      Endpoint: '${Endpoint}'

  CloudTrailNotificationsPolicy:
    Condition: CreateSNSTopic
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - !Ref CloudTrailNotificationsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudTrailPublish"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "SNS:Publish"
            Resource: !Ref CloudTrailNotificationsTopic

Conditions:
  CreateSNSTopic: !Equals [!Ref CreateTopic, "true"]

Outputs:
  RoleARN:
    Description: "The ARN of the IAM Role created for CloudTrail logs."
    Value: !GetAtt CloudLogsRole.Arn

  TopicARN:
    Description: "The ARN of the SNS Topic created for CloudTrail notifications."
    Value: !If [CreateSNSTopic, !Ref CloudTrailNotificationsTopic, !Ref TopicARN]
