AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role for Agentless

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ""
        Parameters:
          - SysdigRoleName
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - SysdigExternalID
          - SysdigTrustedIdentity

    ParameterLabels:
      SysdigRoleName:
        default: "Role Name"
      SysdigExternalID:
        default: "External ID (Sysdig use only)"
      SysdigTrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"

Parameters:
  SysdigRoleName:
    Type: String
    Default: "sysdig-secure"
    Description: The read-only IAM Role that Sysdig will create
  SysdigExternalID:
    Type: String
    Description: Sysdig generated token that proves you own this account
  SysdigTrustedIdentity:
    Type: String
    Description: The Role in Sysdig’s AWS Account with permissions to your account

Resources:
  CloudAgentlessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref SysdigRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Ref SysdigTrustedIdentity
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref SysdigExternalID
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit