AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role used by Sysdig Secure for CSPM

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - RoleName
          - ExternalID
          - TrustedIdentity

    ParameterLabels:
      RoleName:
        default: "Role Name (Sysdig use only)"
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"

Parameters:
  RoleName:
    Type: String
    Description: The read-only IAM Role that Sysdig will create
  ExternalID:
    Type: String
    Description: Sysdig generated token that proves you own this account
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account

Resources:
  CloudAgentlessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Ref TrustedIdentity
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalID
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Policies:
        - PolicyName: !Ref RoleName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "elasticfilesystem:DescribeAccessPoints"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "waf-regional:ListRules"
                  - "waf-regional:ListRuleGroups"
                Resource:
                  - "arn:aws:waf-regional:*:*:rule/*"
                  - "arn:aws:waf-regional:*:*:rulegroup/*"
              - Effect: "Allow"
                Action: "account:GetContactInformation"
                Resource: "*"

Outputs:
  RoleARN:
    Description: ARN of the role created
    Value: !Sub ${CloudAgentlessRole.Arn}