AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role for Agentless
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - RoleName
          - ExternalID
          - TrustedIdentity
          - OrganizationUnitIDs
    ParameterLabels:
      RoleName:
        default: "Role Name (Sysdig use only)"    
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"
      OrganizationUnitIDs:
        default: "Organization Unit IDs (Sysdig use only)"
Parameters:
  RoleName:
    Type: String
    Description: Unique role for monitoring AWS accounts
  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  TrustedIdentity:
    Type: String
    Description: Sysdig Trusted identity required for policy creation
  OrganizationUnitIDs:
    Type: String
    Description: Organization Unit IDs to deploy   
Resources:
  CloudAgentlessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${RoleName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub ${TrustedIdentity}
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${ExternalID}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Policies:
        - PolicyName: !Sub ${RoleName}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "elasticfilesystem:DescribeAccessPoints"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "waf-regional:ListRules"
                  - "waf-regional:ListRuleGroups"
                Resource:
                  - "arn:aws:waf-regional:*:*:rule/*"
                  - "arn:aws:waf-regional:*:*:rulegroup/*"
              - Effect: "Allow"
                Action: "macie2:ListClassificationJobs"
                Resource: "*"
              - Effect: "Allow"
                Action: "lambda:GetRuntimeManagementConfig"
                Resource: "*"
  RoleStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: AgentLessRoleStackSet
      Description: Create a Role in all regions
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - "CAPABILITY_NAMED_IAM"
      AutoDeployment:
        Enabled: false
      Parameters:
        - ParameterKey: RoleName
          ParameterValue: !Ref RoleName
        - ParameterKey: TrustedIdentity
          ParameterValue: !Ref TrustedIdentity
        - ParameterKey: ExternalID
          ParameterValue: !Ref ExternalID        
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Split [ ',', !Ref OrganizationUnitIDs]
          Regions:
            - !Ref "AWS::Region"      
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role for Agentless
        Parameters:
          RoleName:
            Type: String
            Description: Role name
          TrustedIdentity:
            Type: String
            Description: Trusted identity
          ExternalID:
            Type: String
            Description: external ID

        Resources:
          CloudAgentlessRole:
            Type: "AWS::IAM::Role"
            Properties:
              RoleName: !Sub ${RoleName}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: "Allow"
                    Principal:
                      AWS: !Sub ${TrustedIdentity}
                    Action: "sts:AssumeRole"
                    Condition:
                      StringEquals:
                        sts:ExternalId: !Sub ${ExternalID}
              ManagedPolicyArns:
                - arn:aws:iam::aws:policy/SecurityAudit
              Policies:
                - PolicyName: !Sub ${RoleName}
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Effect: "Allow"
                        Action: "elasticfilesystem:DescribeAccessPoints"
                        Resource: "*"
                      - Effect: "Allow"
                        Action:
                          - "waf-regional:ListRules"
                          - "waf-regional:ListRuleGroups"
                        Resource:
                          - "arn:aws:waf-regional:*:*:rule/*"
                          - "arn:aws:waf-regional:*:*:rulegroup/*"
                      - Effect: "Allow"
                        Action: "macie2:ListClassificationJobs"
                        Resource: "*"
                      - Effect: "Allow"
                        Action: "lambda:GetRuntimeManagementConfig"
                        Resource: "*"
