AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge resource that forward CloudTrail logs to Sysdig Secure

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - EventBridgeRoleName
          - ExternalID
          - TrustedIdentity
          - EventBusARN

    ParameterLabels:
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"
      EventBusARN:
        default: "Target Event Bus (Sysdig use only)"
      EventBridgeRoleName:
        default: "Integration Name (Sysdig use only)"

Parameters:
  EventBridgeRoleName:
    Type: String
    Default: "sysdig-secure-cloudtrail"
    Description: A unique identifier used to create an IAM Role and EventBridge Rule
  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  EventBusARN:
    Type: String
    Description: The destination in Sysdig's AWS account where your events are sent

Resources:
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EventBridgeRoleName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
          - Effect: "Allow"
            Principal:
              AWS: !Ref TrustedIdentity
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalID           
      Policies:
        - PolicyName: !Ref EventBridgeRoleName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'events:PutEvents'
                Resource: !Ref EventBusARN
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref EventBridgeRoleName
      Description: Capture all CloudTrail events
      EventPattern:
        detail-type:
          - 'AWS API Call via CloudTrail'
      Targets:
        - Id: !Ref EventBridgeRoleName
          Arn: !Ref EventBusARN
          RoleArn: !GetAtt
            - EventBridgeRole
            - Arn    
