AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridgeRole and EventBridgeRule for falco cloud
Parameters:
  EventBridgeRoleName:
    Type: String
    Default: "sysdig-secure-cloudtrail"
    Description: A unique identifier used to create an IAM Role and EventBridge Rule
  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  EventBusARN:
    Type: String
    Description: The destination in Sysdig's AWS account where your events are sent
  OrganizationUnitIDs:
    Type: String
    Description: Organization Unit IDs to deploy    

Resources:
  EBRuleStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: EBRuleStackSet
      Description: Create a Stackset for creation of resources needed for Threat Detection
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - "CAPABILITY_NAMED_IAM"
      AutoDeployment:
        Enabled: false
      Parameters:
        - ParameterKey: TrustedIdentity
          ParameterValue: !Ref TrustedIdentity
        - ParameterKey: ExternalID
          ParameterValue: !Ref ExternalID
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
        - ParameterKey: EventBusARN
          ParameterValue: !Ref EventBusARN                      
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref OrganizationUnitIDs
          Regions:
            - !Ref "AWS::Region"  
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: Stackset for Threat Detection
        Parameters:
          TrustedIdentity:
            Type: String
            Description: Trusted identity
          ExternalID:
            Type: String
            Description: External ID
          EventBridgeRoleName:
            Type: String
            Description: EventBridge Role Name
          EventBusARN:
            Type: String
            Description: EventBus ARN                        

        Resources:
          EventBridgeRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub ${EventBridgeRoleName}
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Principal:
                      Service: events.amazonaws.com
                    Action: 'sts:AssumeRole'
                  - Effect: "Allow"
                    Principal:
                      AWS: !Sub ${TrustedIdentity}
                    Action: "sts:AssumeRole"
                    Condition:
                      StringEquals:
                        sts:ExternalId: !Sub ${ExternalID}          
              Policies:
                - PolicyName: !Sub ${EventBridgeRoleName}
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Effect: Allow
                        Action: 'events:PutEvents'
                        Resource: !Sub ${EventBusARN}               
          EventBridgeRule:
            Type: "AWS::Events::Rule"
            Properties:
              Name: !Sub ${EventBridgeRoleName}
              Description: Capture all CloudTrail events
              EventPattern:
                detail-type:
                  - 'AWS API Call via CloudTrail'
                  - 'AWS Console Sign In via CloudTrail'
                  - 'AWS Service Event via CloudTrail'
              Targets:
                - Id: !Sub ${EventBridgeRoleName}
                  Arn: !Sub ${EventBusARN}
                  RoleArn: !GetAtt [EventBridgeRole, Arn]
                    
        Outputs:
          RuleARN:
            Description: ARN of the rule created
            Value: !Sub ${EventBridgeRule.Arn}