AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge resources with API Destinations that forward CloudTrail logs
  to Sysdig Secure across AWS Organizations
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sysdig Settings (Do not change)
      Parameters:
      - EventBridgeRoleName
      - ExternalID
      - TrustedIdentity
      - ApiKey
      - IngestionUrl
      - RateLimit
      - Regions
      - OrganizationUnitIDs
      - EventBridgeState
      - EventBridgeEventPattern
    ParameterLabels:
      EventBridgeRoleName:
        default: Integration Name (Sysdig use only)
      ExternalID:
        default: External ID (Sysdig use only)
      TrustedIdentity:
        default: Trusted Identity (Sysdig use only)
      ApiKey:
        default: API Key (Sysdig use only)
      IngestionUrl:
        default: Endpoint URL (Sysdig use only)
      RateLimit:
        default: Rate Limit (Sysdig use only)
      Regions:
        default: EventBridge Regions (Sysdig use only)
      OrganizationUnitIDs:
        default: Organization Unit IDs (Sysdig use only)
      EventBridgeState:
        default: State of the EventBridge Rule (Sysdig use only)
      EventBridgeEventPattern:
        default: Event Pattern (Sysdig use only)
Parameters:
  EventBridgeRoleName:
    Type: String
    Description: A unique identifier used to create an IAM Role and EventBridge Rule
  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  ApiKey:
    Type: String
    Description: API key for Sysdig Secure authentication
  IngestionUrl:
    Type: String
    Description: Sysdig Secure API endpoint URL
  RateLimit:
    Type: Number
    Description: Maximum invocations per second for the API destination
    Default: 300
  Regions:
    Type: String
    Description: Comma separated list of regions to monitor with EventBridge
  OrganizationUnitIDs:
    Type: String
    Description: Comma separated list of Organization Unit IDs to deploy
  EventBridgeState:
    Type: String
    Description: The state of the EventBridge Rule
    Default: ENABLED
    AllowedValues:
    - ENABLED
    - DISABLED
  EventBridgeEventPattern:
    Type: String
    Description: JSON pattern for the EventBridge rule's event pattern
    Default: "{\n  \"detail-type\": [\n    \"AWS API Call via CloudTrail\",\n    \"\
      AWS Console Sign In via CloudTrail\",\n    \"AWS Service Event via CloudTrail\"\
      ,\n    \"Object Access Tier Changed\",\n    \"Object ACL Updated\",\n    \"\
      Object Created\",\n    \"Object Deleted\",\n    \"Object Restore Completed\"\
      ,\n    \"Object Restore Expired\",\n    \"Object Restore Initiated\",\n    \"\
      Object Storage Class Changed\",\n    \"Object Tags Added\",\n    \"Object Tags\
      \ Deleted\",\n    \"GuardDuty Finding\"\n  ]\n}\n"
Resources:
  AdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - sts:AssumeRole
            Resource:
            - arn:aws:iam::*:role/AWSCloudFormationStackSetExecutionRole
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - Fn::GetAtt:
              - AdministrationRole
              - RoleId
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
  MgmtAccEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${EventBridgeRoleName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sts:AssumeRole
        - Effect: Allow
          Principal:
            AWS:
              Fn::Sub: ${TrustedIdentity}
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Fn::Sub: ${ExternalID}
      Policies:
      - PolicyName:
          Fn::Sub: ${EventBridgeRoleName}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: InvokeApiDestination
            Effect: Allow
            Action:
            - events:InvokeApiDestination
            Resource:
            - Fn::Sub: arn:aws:events:*:*:api-destination/${EventBridgeRoleName}-destination/*
          - Sid: CloudTrailEventRuleAccess
            Effect: Allow
            Action:
            - events:DescribeRule
            - events:ListTargetsByRule
            Resource:
            - Fn::Sub: arn:aws:events:*:*:rule/${EventBridgeRoleName}
          - Sid: ValidationAccess
            Effect: Allow
            Action:
            - events:DescribeApiDestination
            - events:DescribeConnection
            Resource: '*'
  MgmtAccEBRuleStackSet:
    Type: AWS::CloudFormation::StackSet
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - W3005
    DependsOn:
    - ExecutionRole
    - AdministrationRole
    Properties:
      StackSetName: MgmtAccEBRuleStackSet
      AdministrationRoleARN:
        Fn::GetAtt:
        - AdministrationRole
        - Arn
      Description: EventBridge Resources that forward CloudTrail logs to Sysdig Secure
      PermissionModel: SELF_MANAGED
      ManagedExecution:
        Active: true
      Capabilities:
      - CAPABILITY_NAMED_IAM
      OperationPreferences:
        MaxConcurrentPercentage: 100
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        RegionConcurrencyType: PARALLEL
      Parameters:
      - ParameterKey: EventBridgeRoleName
        ParameterValue:
          Ref: EventBridgeRoleName
      - ParameterKey: ApiKey
        ParameterValue:
          Ref: ApiKey
      - ParameterKey: IngestionUrl
        ParameterValue:
          Ref: IngestionUrl
      - ParameterKey: RateLimit
        ParameterValue:
          Ref: RateLimit
      - ParameterKey: EventBridgeState
        ParameterValue:
          Ref: EventBridgeState
      - ParameterKey: EventBridgeEventPattern
        ParameterValue:
          Ref: EventBridgeEventPattern
      StackInstancesGroup:
      - DeploymentTargets:
          Accounts:
          - Ref: AWS::AccountId
        Regions:
          Fn::Split:
          - ','
          - Ref: Regions
      TemplateBody: "AWSTemplateFormatVersion: \"2010-09-09\"\nDescription: EventBridge\
        \ Resources that forward CloudTrail logs to Sysdig Secure\nParameters:\n \
        \ EventBridgeRoleName:\n    Type: String\n    Description: A unique identifier\
        \ used to create an IAM Role and EventBridge Rule\n  ApiKey:\n    Type: String\n\
        \    Description: API key for authentication\n  IngestionUrl:\n    Type: String\n\
        \    Description: Target endpoint URL for the API destination\n  RateLimit:\n\
        \    Type: Number\n    Description: Maximum invocations per second for the\
        \ API destination\n  EventBridgeState:\n    Type: String\n    Description:\
        \ The state of the EventBridge Rule\n    Default: ENABLED\n    AllowedValues:\n\
        \      - ENABLED\n      - DISABLED\n  EventBridgeEventPattern:\n    Type:\
        \ String\n    Description: JSON pattern for the EventBridge rule's event pattern\n\
        Resources:\n  EventBridgeConnection:\n    Type: AWS::Events::Connection\n\
        \    Properties:\n      Name: !Sub ${EventBridgeRoleName}-connection\n   \
        \   AuthorizationType: API_KEY\n      AuthParameters:\n        ApiKeyAuthParameters:\n\
        \          ApiKeyName: X-Api-Key\n          ApiKeyValue: !Ref ApiKey\n\n \
        \ EventBridgeApiDestination:\n    Type: AWS::Events::ApiDestination\n    Properties:\n\
        \      Name: !Sub ${EventBridgeRoleName}-destination\n      ConnectionArn:\
        \ !GetAtt EventBridgeConnection.Arn\n      InvocationEndpoint: !Ref IngestionUrl\n\
        \      HttpMethod: POST\n      InvocationRateLimitPerSecond: !Ref RateLimit\n\
        \n  EventBridgeRule:\n    Type: AWS::Events::Rule\n    Properties:\n     \
        \ Name: !Sub ${EventBridgeRoleName}\n      Description: Capture all CloudTrail\
        \ events\n      EventPattern: !Ref EventBridgeEventPattern\n      State: !Ref\
        \ EventBridgeState\n      Targets:\n        - Id: !Sub ${EventBridgeRoleName}\n\
        \          Arn: !GetAtt EventBridgeApiDestination.Arn\n          RoleArn:\
        \ !Sub \"arn:aws:iam::${AWS::AccountId}:role/${EventBridgeRoleName}\"\n"
  EBRoleStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: EBRoleStackSet
      Description: IAM Role used to forward CloudTrail logs to Sysdig Secure
      PermissionModel: SERVICE_MANAGED
      Capabilities:
      - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
      Parameters:
      - ParameterKey: EventBridgeRoleName
        ParameterValue:
          Ref: EventBridgeRoleName
      StackInstancesGroup:
      - DeploymentTargets:
          OrganizationalUnitIds:
            Fn::Split:
            - ','
            - Ref: OrganizationUnitIDs
        Regions:
        - Ref: AWS::Region
      TemplateBody: "AWSTemplateFormatVersion: \"2010-09-09\"\nDescription: IAM Role\
        \ used for EventBridge API Destinations\nParameters:\n  EventBridgeRoleName:\n\
        \    Type: String\n    Description: A unique identifier used to create IAM\
        \ Role for EventBridge\nResources:\n  EventBridgeRole:\n    Type: AWS::IAM::Role\n\
        \    Properties:\n      RoleName: !Ref EventBridgeRoleName\n      AssumeRolePolicyDocument:\n\
        \        Version: \"2012-10-17\"\n        Statement:\n          - Effect:\
        \ Allow\n            Principal:\n              Service: events.amazonaws.com\n\
        \            Action: 'sts:AssumeRole'\n      Policies:\n        - PolicyName:\
        \ !Ref EventBridgeRoleName\n          PolicyDocument:\n            Version:\
        \ \"2012-10-17\"\n            Statement:\n              - Sid: \"InvokeApiDestination\"\
        \n                Effect: Allow\n                Action:\n               \
        \   - \"events:InvokeApiDestination\"\n                Resource:\n       \
        \           - !Sub \"arn:aws:events:*:*:api-destination/${EventBridgeRoleName}-destination/*\"\
        \n              - Sid: \"CloudTrailEventRuleAccess\"\n                Effect:\
        \ Allow\n                Action:\n                  - \"events:DescribeRule\"\
        \n                  - \"events:ListTargetsByRule\"\n                Resource:\n\
        \                  - !Sub \"arn:aws:events:*:*:rule/${EventBridgeRoleName}\"\
        \n              - Sid: \"ValidationAccess\"\n                Effect: Allow\n\
        \                Action:\n                  - \"events:DescribeApiDestination\"\
        \n                  - \"events:DescribeConnection\"\n                Resource:\
        \ \"*\"\n"
  EBApiDestStackSet:
    Type: AWS::CloudFormation::StackSet
    DependsOn: EBRoleStackSet
    Properties:
      StackSetName: EBApiDestStackSet
      Description: EventBridge Resources with API Destinations that forward CloudTrail
        logs to Sysdig Secure
      PermissionModel: SERVICE_MANAGED
      Capabilities:
      - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        RegionConcurrencyType: PARALLEL
      Parameters:
      - ParameterKey: EventBridgeRoleName
        ParameterValue:
          Ref: EventBridgeRoleName
      - ParameterKey: ApiKey
        ParameterValue:
          Ref: ApiKey
      - ParameterKey: IngestionUrl
        ParameterValue:
          Ref: IngestionUrl
      - ParameterKey: RateLimit
        ParameterValue:
          Ref: RateLimit
      - ParameterKey: EventBridgeState
        ParameterValue:
          Ref: EventBridgeState
      - ParameterKey: EventBridgeEventPattern
        ParameterValue:
          Ref: EventBridgeEventPattern
      StackInstancesGroup:
      - DeploymentTargets:
          OrganizationalUnitIds:
            Fn::Split:
            - ','
            - Ref: OrganizationUnitIDs
        Regions:
          Fn::Split:
          - ','
          - Ref: Regions
      TemplateBody: "AWSTemplateFormatVersion: \"2010-09-09\"\nDescription: EventBridge\
        \ Resources with API Destinations that forward CloudTrail logs to Sysdig Secure\n\
        Parameters:\n  EventBridgeRoleName:\n    Type: String\n    Description: A\
        \ unique identifier used to create an IAM Role and EventBridge Rule\n  ApiKey:\n\
        \    Type: String\n    Description: API key for Sysdig Secure authentication\n\
        \  IngestionUrl:\n    Type: String\n    Description: Sysdig Secure API endpoint\
        \ URL\n  RateLimit:\n    Type: Number\n    Description: Maximum invocations\
        \ per second for the API destination\n  EventBridgeState:\n    Type: String\n\
        \    Description: The state of the EventBridge Rule\n    Default: ENABLED\n\
        \    AllowedValues:\n      - ENABLED\n      - DISABLED\n  EventBridgeEventPattern:\n\
        \    Type: String\n    Description: JSON pattern for the EventBridge rule's\
        \ event pattern\nResources:\n  EventBridgeConnection:\n    Type: AWS::Events::Connection\n\
        \    Properties:\n      Name: !Sub ${EventBridgeRoleName}-connection\n   \
        \   AuthorizationType: API_KEY\n      AuthParameters:\n        ApiKeyAuthParameters:\n\
        \          ApiKeyName: X-Api-Key\n          ApiKeyValue: !Ref ApiKey\n\n \
        \ EventBridgeApiDestination:\n    Type: AWS::Events::ApiDestination\n    Properties:\n\
        \      Name: !Sub ${EventBridgeRoleName}-destination\n      ConnectionArn:\
        \ !GetAtt EventBridgeConnection.Arn\n      InvocationEndpoint: !Ref IngestionUrl\n\
        \      HttpMethod: POST\n      InvocationRateLimitPerSecond: !Ref RateLimit\n\
        \n  EventBridgeRule:\n    Type: AWS::Events::Rule\n    Properties:\n     \
        \ Name: !Ref EventBridgeRoleName\n      Description: Capture all CloudTrail\
        \ events for Sysdig Secure\n      EventPattern: !Ref EventBridgeEventPattern\n\
        \      State: !Ref EventBridgeState\n      Targets:\n        - Id: !Ref EventBridgeRoleName\n\
        \          Arn: !GetAtt EventBridgeApiDestination.Arn\n          RoleArn:\
        \ !Sub \"arn:aws:iam::${AWS::AccountId}:role/${EventBridgeRoleName}\"\n"
