AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Sysdig Secure for cloud deployment for Organizational Setup.
  Before launching this template, launch 'sysdig_provisioning.sh' script to prepare Sysdig backend.
  

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Compliance Role"
        Parameters:
          - SysdigRoleName
          - SysdigExternalID
          - SysdigTrustedIdentity

      - Label:
          default: "AWS Organization Parameters for Sysdig"
        Parameters:
          - SysdigManagementAccountRole
          - AssumeRoleBenefficiary
          - CloudtrailS3Arn

#    ParameterLabels:
#      SysdigRoleName:
#        default: "Sysdig Role Name"
#      SysdigExternalID:
#        default: "Sysdig External ID"
#      SysdigTrustedIdentity:
#        default: "Sysdig Trusted Identity"
#      ECRImageScanningDeploy:
#        default: "Do you want to deploy ECR Image Registry Scanning?"
#      ECSImageScanningDeploy:
#        default: "Do you want to deploy Fargate Image Scanning?"
#      ExistentECSCluster:
#        default: "ECS Cluster Name"
#      ExistentECSClusterVPC:
#        default: "VPC Id"
#      ExistentECSClusterPrivateSubnets:
#        default: "Private subnet Id's"
#      ExistentCloudTrailSNSTopic:
#        default: "CloudTrail SNS Topic"



Parameters:
  # threat-detection, compliance, identity&access
  SysdigManagementAccountRole:
    Type: String
    Default: "SysdigManagementAccountRole"
    Description: Name of the role to be created on the organization management account
  AssumeRoleBenefficiary:
    Type: String
    Description: Role to which we will allow `sts:assumeRole` permissions for the SysdigManagementAccountRole
  CloudtrailS3Arn:
    Type: String
    Description: Arn of the S3 that contains the cloudtrail events

  # compliance
  OrganizationaUnitId:
    Type: String
    Description: Organizational Unit Id where StackSet is to be applied
    AllowedPattern: '^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})$'
  SysdigRoleName:
    Type: String
    Default: "SysdigComplianceRole"
    Description: Unique role for monitoring AWS accounts
  SysdigExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  SysdigTrustedIdentity:
    Type: String
    Description: Sysdig Trusted identity required for policy creation

Resources:
  SysdigManagementRole:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      TemplateURL: ./OrgManagementAccountSysdigRole.yaml
      StackSetName: SysdigManagementAccountData
      Description: Prepare a role in Organization Management Account
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: False
      ManagedExecution:
        Active: true
      Tags:
        - Key: product
          Value: sysdig-secure-for-cloud
        - Key: stackname
          Value: !Sub "${AWS::StackName}"
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Sub "${AWS::AccountId}"
          Regions:
            - !Sub "${AWS::Region}"
      Parameters:
        - ParameterKey: SysdigManagementAccountRole
          ParameterValue: !Ref SysdigManagementAccountRole
        - ParameterKey: AssumeRoleBenefficiary
          ParameterValue: !Ref AssumeRoleBenefficiary
        - ParameterKey: CloudtrailS3Arn
          ParameterValue: !Ref CloudtrailS3Arn

  SysdigComplianceRoleStackSet:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      TemplateURL: ../general_templates/ComplianceAgentlessRole.yaml
      StackSetName: SysdigComplianceRole
      Description: Deploy a SysdigRole for Security Audit tasks
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: True
        RetainStacksOnAccountRemoval: False
      ManagedExecution:
        Active: true
      Tags:
        - Key: product
          Value: sysdig-secure-for-cloud
        - Key: stackname
          Value: !Sub "${AWS::StackName}"
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref OrganizationaUnitId
          Regions:
            - !Sub "${AWS::Region}"
      Parameters:
        - ParameterKey: SysdigRoleName
          ParameterValue: !Ref SysdigRoleName
        - ParameterKey: SysdigExternalID
          ParameterValue: !Ref SysdigExternalID
        - ParameterKey: SysdigTrustedIdentity
          ParameterValue: !Ref SysdigTrustedIdentity