AWSTemplateFormatVersion: "2010-09-09"
Description: CodeBuild for performing image scanning with Sysdig Secure

Parameters:
  SysdigSecureEndpointSsm:
    Type: AWS::SSM::Parameter::Name
    Description: "Name of the parameter in SSM containing the Sysdig Secure Endpoint URL"
  SysdigSecureAPITokenSsm:
    Type: AWS::SSM::Parameter::Name
    Description: "Name of the parameter in SSM containing the Sysdig Secure API Token"
  VerifySSL:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"
  LogRetention:
    Type: Number
    Default: 30
    Description: Days to keep logs from builds
  NamingPrefix:
    Type: String
    Default: "SysdigCloud"
    Description: Prefix for resource names. Use the default unless you need to install multiple instances, and modify the deployment at the main account accordingly
    MinLength: 1
    MaxLength: 32
    AllowedPattern : "^[a-zA-Z0-9]+$"
    ConstraintDescription: Must enter a naming prefix up to 32 alphanumeric characters

Conditions:
  VerifySSL: !Equals [!Ref VerifySSL, "Yes"]

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: !Ref LogRetention

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "IAM::Role which allows to run the CodeBuild Job to perform the ECR scanning"
      Path: /
      Policies:
        - PolicyName: LogsPublisher
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroup}
                  - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroup}:*

        - PolicyName: ParameterReader
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:DescribeParameters"
                  - "ssm:GetParameter"
                  - "ssm:GetParameters"
                Resource:
                  - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SysdigSecureEndpointSsm}
                  - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SysdigSecureAPITokenSsm}

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${NamingPrefix}-CloudScanningProject"
      Description: "CodeBuild project which scans images using inline technology"
      ServiceRole: !Ref ServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:3.0
        PrivilegedMode: true
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LogGroup
          Status: ENABLED
      Source:
        Type: NO_SOURCE
        BuildSpec: !Sub
          - |
            version: 0.2

            env:
              variables:
                SCAN_IMAGE_NAME: "quay.io/sysdig/secure-inline-scan:2"
              parameter-store:
                SYSDIG_SECURE_ENDPOINT: ${SysdigSecureEndpointSsm}
                SYSDIG_SECURE_TOKEN: ${SysdigSecureAPITokenSsm}

            phases:
              build:
                commands:
                - |
                  if [ -z "$REGISTRY_AUTH" ]; then
                    docker run --rm -e SYSDIG_ADDED_BY=$SYSDIG_ADDED_BY $SCAN_IMAGE_NAME -s $SYSDIG_SECURE_ENDPOINT ${SkipTLSFlag} --sysdig-token $SYSDIG_SECURE_TOKEN $IMAGE_TO_SCAN --annotations=aws-account=$EVENT_ACCOUNT,aws-region=$EVENT_REGION
                  else
                    docker run --rm -e SYSDIG_ADDED_BY=$SYSDIG_ADDED_BY $SCAN_IMAGE_NAME -s $SYSDIG_SECURE_ENDPOINT ${SkipTLSFlag} --sysdig-token $SYSDIG_SECURE_TOKEN --registry-auth-basic "$(echo $REGISTRY_AUTH | base64 -d)" $IMAGE_TO_SCAN --annotations=aws-account=$EVENT_ACCOUNT,aws-region=$EVENT_REGION
                  fi
          - SkipTLSFlag: !If [ VerifySSL, "", " --sysdig-skip-tls" ]

Outputs:
  BuildProject:
    Description: The name of the CodeBuild project
    Value: !Ref BuildProject
