AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig IAM Role for Security Audit
Parameters:
  SysdigRoleName:
    Type: String
    Default: "SysdigAgentlessRole"
    Description: Unique role for monitoring AWS accounts
  SysdigExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  SysdigTrustedIdentity:
    Type: String
    Description: Sysdig Trusted identity required for policy creation

Resources:
  SysdigCloudBench:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref SysdigRoleName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: [ !Ref SysdigTrustedIdentity ]
            Action: [ 'sts:AssumeRole' ]
            Condition:
              StringEquals:
                sts:ExternalId: !Ref SysdigExternalID
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/SecurityAudit"