AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig Secure secrets to integrate with CloudVision


Parameters:
  SysdigSecureAPIToken:
    Type: String
    Description: "Enter your Sysdig Secure API Token"
  SysdigSecureEndpoint:
    Type: String
    Description: "Enter your Sysdig Secure Endpoint"
    Default: "https://secure.sysdig.com"

Resources:
  SysdigSecureAPITokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SysdigSecureAPIToken
      Description: "Sysdig Secure API Token"
      Type: String
      Value: !Ref SysdigSecureAPIToken

  SysdigSecureEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SysdigSecureEndpoint
      Description: "Sysdig Secure endpoint"
      Type: String
      Value: !Ref SysdigSecureEndpoint