AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role for Agentless
Parameters:
  SysdigRoleName:
    Type: String
    Default: "SysdigAgentlessRole"
    Description: Unique role for monitoring AWS accounts
  SysdigExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  SysdigTrustedIdentity:
    Type: String
    Description: Sysdig Trusted identity required for policy creation
  SysdigEBName:
    Type: String
    Default: "sysdig"
    Description: Unique name for role and policy
  SysdigExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  SysdigEventBusARN:
    Type: String
    Description: Sysdig event bus ARN
  DeadLetterQueueARN:
    Type: String
    Description: DeadLetterQueueARN ARN

Conditions:
  IsDeadLetterQueueARNNotEmpty:
    !Not [!Equals [ !Ref DeadLetterQueueARN, ""]]

Resources:
  CloudAgentlessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref SysdigRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: !Ref SysdigTrustedIdentity
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref SysdigExternalID
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref SysdigEBName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Ref SysdigEBName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'events:PutEvents'
                Resource: !Ref SysdigEventBusARN
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref SysdigEBName
      Description: Capture all CloudTrail events
      EventPattern:
        detail-type:
          - 'AWS API Call via CloudTrail'
      Targets:
        - Id: !Ref SysdigEBName
          Arn: !Ref SysdigEventBusARN
          RoleArn: !GetAtt
            - EventBridgeRole
            - Arn
          DeadLetterConfig:
            !If
              - IsDeadLetterQueueARNNotEmpty
              -
                Arn: !Ref DeadLetterQueueARN
              - !Ref "AWS::NoValue"