AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge resources that forward CloudTrail logs to Sysdig Secure via API Destination

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - EventBridgeRoleName
          - ExternalID
          - TrustedIdentity
          - ApiKey
          - IngestionUrl
          - RateLimit
          - EventBridgeState
          - EventBridgeEventPattern

    ParameterLabels:
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"
      ApiKey:
        default: "API Key (Sysdig use only)"
      IngestionUrl:
        default: "Ingestion URL (Sysdig use only)"
      RateLimit:
        default: "Rate Limit (Sysdig use only)"
      EventBridgeRoleName:
        default: "Integration Name (Sysdig use only)"
      EventBridgeState:
        default: "State of the EventBridge Rule (Sysdig use only)"
      EventBridgeEventPattern:
        default: "Event Pattern (Sysdig use only)"

Parameters:
  EventBridgeRoleName:
    Type: String
    Description: A unique identifier used to create an IAM Role and EventBridge Rule
  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  ApiKey:
    Type: String
    Description: API key for Sysdig Secure authentication
  IngestionUrl:
    Type: String
    Description: Sysdig Secure API ingestion URL
  RateLimit:
    Type: Number
    Description: Maximum invocations per second for the API destination
    Default: 300
  EventBridgeState:
    Type: String
    Description: The state of the EventBridge Rule
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
  EventBridgeEventPattern:
    Type: String
    Description: JSON pattern for the EventBridge rule's event pattern
    Default: |
      {
        "detail-type": [
          "AWS API Call via CloudTrail",
          "AWS Console Sign In via CloudTrail",
          "AWS Service Event via CloudTrail",
          "Object Access Tier Changed",
          "Object ACL Updated",
          "Object Created",
          "Object Deleted",
          "Object Restore Completed",
          "Object Restore Expired",
          "Object Restore Initiated",
          "Object Storage Class Changed",
          "Object Tags Added",
          "Object Tags Deleted",
          "GuardDuty Finding"
        ]
      }

Resources:
  EventBridgeConnection:
    Type: AWS::Events::Connection
    Properties:
      Name: !Sub ${EventBridgeRoleName}-connection
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKey:
          Key: X-Api-Key
          Value: !Ref ApiKey

  EventBridgeApiDestination:
    Type: AWS::Events::ApiDestination
    Properties:
      Name: !Sub ${EventBridgeRoleName}-destination
      ConnectionArn: !GetAtt EventBridgeConnection.Arn
      InvocationEndpoint: !Ref IngestionUrl
      HttpMethod: POST
      InvocationRateLimitPerSecond: !Ref RateLimit

  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EventBridgeRoleName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
          - Effect: "Allow"
            Principal:
              AWS: !Ref TrustedIdentity
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalID
      Policies:
        - PolicyName: !Ref EventBridgeRoleName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "InvokeApiDestination"
                Effect: Allow
                Action:
                  - "events:InvokeApiDestination"
                Resource:
                  - !Sub "arn:aws:events:*:*:api-destination/${EventBridgeRoleName}-destination/*"
              - Sid: "CloudTrailEventRuleAccess"
                Effect: Allow
                Action:
                  - "events:DescribeRule"
                  - "events:ListTargetsByRule"
                Resource:
                  - !Sub "arn:aws:events:*:*:rule/${EventBridgeRoleName}"
              - Sid: "ValidationAccess"
                Effect: Allow
                Action:
                  - "events:DescribeApiDestination"
                  - "events:DescribeConnection"
                Resource: "*"

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref EventBridgeRoleName
      Description: Capture all CloudTrail events for Sysdig Secure
      EventPattern: !Ref EventBridgeEventPattern
      State: !Ref EventBridgeState
      Targets:
        - Id: !Ref EventBridgeRoleName
          Arn: !GetAtt EventBridgeApiDestination.Arn
          RoleArn: !GetAtt EventBridgeRole.Arn
