AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge resources with API Destinations that forward CloudTrail logs to Sysdig Secure across AWS Organizations

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - EventBridgeRoleName
          - ExternalID
          - TrustedIdentity
          - ApiKey
          - EndpointUrl
          - RateLimit
          - Regions
          - OrganizationUnitIDs
          - EventBridgeState
          - EventBridgeEventPattern

    ParameterLabels:
      EventBridgeRoleName:
        default: "Integration Name (Sysdig use only)"
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"
      ApiKey:
        default: "API Key (Sysdig use only)"
      EndpointUrl:
        default: "Endpoint URL (Sysdig use only)"
      RateLimit:
        default: "Rate Limit (Sysdig use only)"
      Regions:
        default: "EventBridge Regions (Sysdig use only)"
      OrganizationUnitIDs:
        default: "Organization Unit IDs (Sysdig use only)"
      EventBridgeState:
        default: "State of the EventBridge Rule (Sysdig use only)"
      EventBridgeEventPattern:
        default: "Event Pattern (Sysdig use only)"

Parameters:
  EventBridgeRoleName:
    Type: String
    Description: A unique identifier used to create an IAM Role and EventBridge Rule
  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation
  TrustedIdentity:
    Type: String
    Description: The Role in Sysdig's AWS Account with permissions to your account
  ApiKey:
    Type: String
    Description: API key for Sysdig Secure authentication
  EndpointUrl:
    Type: String
    Description: Sysdig Secure API endpoint URL
  RateLimit:
    Type: Number
    Description: Maximum invocations per second for the API destination
    Default: 300
  Regions:
    Type: String
    Description: Comma separated list of regions to monitor with EventBridge
  OrganizationUnitIDs:
    Type: String
    Description: Comma separated list of Organization Unit IDs to deploy
  EventBridgeState:
    Type: String
    Description: The state of the EventBridge Rule
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
  EventBridgeEventPattern:
    Type: String
    Description: JSON pattern for the EventBridge rule's event pattern
    Default: |
      {
        "detail-type": [
          "AWS API Call via CloudTrail",
          "AWS Console Sign In via CloudTrail",
          "AWS Service Event via CloudTrail",
          "Object Access Tier Changed",
          "Object ACL Updated",
          "Object Created",
          "Object Deleted",
          "Object Restore Completed",
          "Object Restore Expired",
          "Object Restore Initiated",
          "Object Storage Class Changed",
          "Object Tags Added",
          "Object Tags Deleted",
          "GuardDuty Finding"
        ]
      }

Resources:
  # CloudFormation StackSet Administration Role
  AdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - "arn:*:iam::*:role/AWSCloudFormationStackSetExecutionRole"

  # CloudFormation StackSet Execution Role
  ExecutionRole:
    Type: AWS::IAM::Role   
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt AdministrationRole.RoleId
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # EventBridge Role in management account
  MgmtAccEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EventBridgeRoleName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
          - Effect: "Allow"
            Principal:
              AWS: !Sub ${TrustedIdentity}
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${ExternalID}  
      Policies:
        - PolicyName: !Sub ${EventBridgeRoleName}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "InvokeApiDestination"
                Effect: Allow
                Action:
                  - "events:InvokeApiDestination"
                Resource:
                  - !Sub "arn:aws:events:*:*:api-destination/${EventBridgeRoleName}-destination/*"
              - Sid: "CloudTrailEventRuleAccess"
                Effect: Allow
                Action:
                  - "events:DescribeRule"
                  - "events:ListTargetsByRule"
                Resource:
                  - !Sub "arn:aws:events:*:*:rule/${EventBridgeRoleName}"
              - Sid: "ValidationAccess"
                Effect: Allow
                Action:
                  - "events:DescribeApiDestination"
                  - "events:DescribeConnection"
                Resource: "*"

  MgmtAccEBRuleStackSet:
    Type: AWS::CloudFormation::StackSet
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3005
    DependsOn: 
      - ExecutionRole
      - AdministrationRole
    Properties:
      StackSetName: MgmtAccEBRuleStackSet
      AdministrationRoleARN: !GetAtt AdministrationRole.Arn
      Description: EventBridge Resources that forward CloudTrail logs to Sysdig Secure
      PermissionModel: SELF_MANAGED
      ManagedExecution:
        Active: true      
      Capabilities:
        - CAPABILITY_NAMED_IAM              
      OperationPreferences:
        MaxConcurrentPercentage: 100
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        RegionConcurrencyType: PARALLEL
      Parameters:
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
        - ParameterKey: ApiKey
          ParameterValue: !Ref ApiKey
        - ParameterKey: EndpointUrl
          ParameterValue: !Ref EndpointUrl
        - ParameterKey: RateLimit
          ParameterValue: !Ref RateLimit
        - ParameterKey: EventBridgeState
          ParameterValue: !Ref EventBridgeState
        - ParameterKey: EventBridgeEventPattern
          ParameterValue: !Ref EventBridgeEventPattern                     
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts: 
              - !Ref AWS::AccountId             
          Regions: !Split [ ",", !Ref Regions]
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: EventBridge Resources that forward CloudTrail logs to Sysdig Secure
        Parameters:
          EventBridgeRoleName:
            Type: String
            Description: A unique identifier used to create an IAM Role and EventBridge Rule
          ApiKey:
            Type: String
            Description: API key for authentication
          EndpointUrl:
            Type: String
            Description: Target endpoint URL for the API destination
          RateLimit:
            Type: Number
            Description: Maximum invocations per second for the API destination
          EventBridgeState:
            Type: String
            Description: The state of the EventBridge Rule
            Default: ENABLED
            AllowedValues:
              - ENABLED
              - DISABLED
          EventBridgeEventPattern:
            Type: String
            Description: JSON pattern for the EventBridge rule's event pattern
        Resources:
          EventBridgeConnection:
            Type: AWS::Events::Connection
            Properties:
              Name: !Sub ${EventBridgeRoleName}-connection
              AuthorizationType: API_KEY
              AuthParameters:
                ApiKey:
                  Key: x-api-key
                  Value: !Ref ApiKey

          EventBridgeApiDestination:
            Type: AWS::Events::ApiDestination
            Properties:
              Name: !Sub ${EventBridgeRoleName}-destination
              ConnectionArn: !GetAtt EventBridgeConnection.Arn
              InvocationEndpoint: !Ref EndpointUrl
              HttpMethod: POST
              InvocationRateLimitPerSecond: !Ref RateLimit

          EventBridgeRule:
            Type: AWS::Events::Rule
            Properties:
              Name: !Sub ${EventBridgeRoleName}
              Description: Capture all CloudTrail events
              EventPattern: !Ref EventBridgeEventPattern
              State: !Ref EventBridgeState
              Targets:
                - Id: !Sub ${EventBridgeRoleName}
                  Arn: !GetAtt EventBridgeApiDestination.Arn
                  RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${EventBridgeRoleName}"

  # StackSet for member accounts - Role deployment
  EBRoleStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: EBRoleStackSet
      Description: IAM Role used to forward CloudTrail logs to Sysdig Secure
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - "CAPABILITY_NAMED_IAM"
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false         
      ManagedExecution:
        Active: true        
      OperationPreferences:
        MaxConcurrentPercentage: 100
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
      Parameters:
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Split [ ",", !Ref OrganizationUnitIDs]
          Regions: [!Ref "AWS::Region"]
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: IAM Role used for EventBridge API Destinations
        Parameters:
          EventBridgeRoleName:
            Type: String
            Description: A unique identifier used to create IAM Role for EventBridge
        Resources:
          EventBridgeRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Ref EventBridgeRoleName
              AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Principal:
                      Service: events.amazonaws.com
                    Action: 'sts:AssumeRole'
              Policies:
                - PolicyName: !Ref EventBridgeRoleName
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Sid: "InvokeApiDestination"
                        Effect: Allow
                        Action:
                          - "events:InvokeApiDestination"
                        Resource: !Sub "arn:aws:events:*:*:api-destination/${EventBridgeRoleName}-destination/*"
                      - Sid: "ValidationAccess"
                        Effect: Allow
                        Action:
                          - "events:DescribeApiDestination"
                          - "events:DescribeConnection"
                        Resource: "*"

  # StackSet for member accounts - EventBridge resources deployment
  EBApiDestStackSet:
    Type: AWS::CloudFormation::StackSet
    DependsOn: EBRoleStackSet
    Properties:
      StackSetName: EBApiDestStackSet
      Description: EventBridge Resources with API Destinations that forward CloudTrail logs to Sysdig Secure
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - "CAPABILITY_NAMED_IAM"
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false         
      ManagedExecution:
        Active: true        
      OperationPreferences:
        MaxConcurrentPercentage: 100
        ConcurrencyMode: SOFT_FAILURE_TOLERANCE
        RegionConcurrencyType: PARALLEL
      Parameters:
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
        - ParameterKey: ApiKey
          ParameterValue: !Ref ApiKey
        - ParameterKey: EndpointUrl
          ParameterValue: !Ref EndpointUrl
        - ParameterKey: RateLimit
          ParameterValue: !Ref RateLimit
        - ParameterKey: EventBridgeState
          ParameterValue: !Ref EventBridgeState
        - ParameterKey: EventBridgeEventPattern
          ParameterValue: !Ref EventBridgeEventPattern
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Split [ ",", !Ref OrganizationUnitIDs]
          Regions: !Split [ ",", !Ref Regions]
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: EventBridge Resources with API Destinations that forward CloudTrail logs to Sysdig Secure
        Parameters:
          EventBridgeRoleName:
            Type: String
            Description: A unique identifier used to create an IAM Role and EventBridge Rule
          ApiKey:
            Type: String
            Description: API key for Sysdig Secure authentication
          EndpointUrl:
            Type: String
            Description: Sysdig Secure API endpoint URL
          RateLimit:
            Type: Number
            Description: Maximum invocations per second for the API destination
          EventBridgeState:
            Type: String
            Description: The state of the EventBridge Rule
            Default: ENABLED
            AllowedValues:
              - ENABLED
              - DISABLED
          EventBridgeEventPattern:
            Type: String
            Description: JSON pattern for the EventBridge rule's event pattern
        Resources:
          EventBridgeConnection:
            Type: AWS::Events::Connection
            Properties:
              Name: !Sub ${EventBridgeRoleName}-connection
              AuthorizationType: API_KEY
              AuthParameters:
                ApiKey:
                  Key: x-api-key
                  Value: !Ref ApiKey

          EventBridgeApiDestination:
            Type: AWS::Events::ApiDestination
            Properties:
              Name: !Sub ${EventBridgeRoleName}-destination
              ConnectionArn: !GetAtt EventBridgeConnection.Arn
              InvocationEndpoint: !Ref EndpointUrl
              HttpMethod: POST
              InvocationRateLimitPerSecond: !Ref RateLimit

          EventBridgeRule:
            Type: AWS::Events::Rule
            Properties:
              Name: !Ref EventBridgeRoleName
              Description: Capture all CloudTrail events for Sysdig Secure
              EventPattern: !Ref EventBridgeEventPattern
              State: !Ref EventBridgeState
              Targets:
                - Id: !Ref EventBridgeRoleName
                  Arn: !GetAtt EventBridgeApiDestination.Arn
                  RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${EventBridgeRoleName}"
