AWSTemplateFormatVersion: "2010-09-09"
Description: CloudTrail configuration for Cloud Connector

Parameters:
  CloudTrailLogRetention:
    Type: Number
    Default: 5
    Description: Days to keep logs from CloudTrail in s3 bucket

Resources:
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref CloudTrailLogRetention
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref CloudTrailLoggingBucket
        LogFilePrefix: sysdig-cloudtrail-bucket-logs
  CloudTrailLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AWSCloudTrailAclCheck20150319"
            Action:
              - "s3:GetBucketAcl"
            Effect: "Allow"
            Resource: !GetAtt CloudTrailBucket.Arn
            Principal:
              Service: "cloudtrail.amazonaws.com"
          - Sid: "AWSCloudTrailWrite20150319"
            Action:
              - "s3:PutObject"
            Effect: "Allow"
            Resource: !Sub "${CloudTrailBucket.Arn}/AWSLogs/${AWS::AccountId}/*"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Condition:
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-CloudConnector"

  SNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AWSCloudTrailSNSPolicy20131101"
            Effect: "Allow"
            Principal:
               Service: "cloudtrail.amazonaws.com"
            Action: "SNS:Publish"
            Resource: !Ref SNSTopic

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Enabled: True
      EnableKeyRotation: False
      KeyPolicy:
        Version: '2012-10-17'
        Id: Key policy created by CloudTrail
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS:
            - !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: "*"
        - Sid: Allow CloudTrail to encrypt logs
          Effect: Allow
          Principal:
            Service:
            - cloudtrail.amazonaws.com
          Action: kms:GenerateDataKey*
          Resource: "*"
          Condition:
            StringLike:
              kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*
        - Sid: Allow CloudTrail to describe key
          Effect: Allow
          Principal:
            Service:
            - cloudtrail.amazonaws.com
          Action: kms:DescribeKey
          Resource: "*"
        - Sid: Allow principals in the account to decrypt log files
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - kms:Decrypt
          - kms:ReEncryptFrom
          Resource: "*"
          Condition:
            StringEquals:
              kms:CallerAccount: !Sub ${AWS::AccountId}
            StringLike:
              kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*
        - Sid: Allow alias creation during setup
          Effect: Allow
          Principal:
            AWS: "*"
          Action: kms:CreateAlias
          Resource: "*"
          Condition:
            StringEquals:
              kms:ViaService: !Sub ec2.${AWS::Region}.amazonaws.com
              kms:CallerAccount: !Sub ${AWS::AccountId}
        - Sid: Enable cross account log decryption
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - kms:Decrypt
          - kms:ReEncryptFrom
          Resource: "*"
          Condition:
            StringEquals:
              kms:CallerAccount: !Sub ${AWS::AccountId}
            StringLike:
              kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*

  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-CloudTrail"
      TargetKeyId: !Ref KMSKey

  Trail:
    Type: AWS::CloudTrail::Trail
    DependsOn:
      - BucketPolicy
      - SNSPolicy
    Properties:
      TrailName: !Sub "${AWS::StackName}-Trail"
      IsLogging: Yes
      IsMultiRegionTrail: Yes
      IncludeGlobalServiceEvents: Yes
      EnableLogFileValidation: Yes
      KMSKeyId: !Ref KMSKey
      S3BucketName: !Ref CloudTrailBucket
      SnsTopicName: !Ref SNSTopic

Outputs:
  Topic:
    Description: SNS Topic where CloudTrail events are published
    Value: !Ref SNSTopic
