AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig for Cloud - AWS Edition

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings"
        Parameters:
          - SysdigSecureEndpoint
          - SysdigSecureAPIToken
          - SysdigRoleName
          - SysdigExternalID
          - SysdigTrustedIdentity

      - Label:
          default: "Modules to Deploy"
        Parameters:
          - CloudConnectorDeploy
          - ECRImageScanningDeploy
          - ECSImageScanningDeploy

      - Label:
          default: "Existing Infrastructure"
        Parameters:
          - ExistentECSCluster
          - ExistentECSClusterVPC
          - ExistentECSClusterPrivateSubnets
          - ExistentCloudTrailSNSTopic

    ParameterLabels:
      SysdigSecureEndpoint:
        default: "Sysdig Secure Endpoint"
      SysdigSecureAPIToken:
        default: "Sysdig Secure API Token"
      SysdigRoleName:
        default: "Sysdig Role Name"
      SysdigExternalID:
        default: "Sysdig External ID"
      SysdigTrustedIdentity:
        default: "Sysdig Trusted Identity"
      CloudConnectorDeploy:
        default: "Do you want to deploy Real-Time Threat Investigation based on CloudTrail?"
      ECRImageScanningDeploy:
        default: "Do you want to deploy ECR Image Registry Scanning?"
      ECSImageScanningDeploy:
        default: "Do you want to deploy Fargate Image Scanning?"
      ExistentECSCluster:
        default: "ECS Cluster Name"
      ExistentECSClusterVPC:
        default: "VPC Id"
      ExistentECSClusterPrivateSubnets:
        default: "Private subnet Id's"
      ExistentCloudTrailSNSTopic:
        default: "CloudTrail SNS Topic"

Parameters:
  CloudConnectorDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECRImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECSImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ExistentECSCluster:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterVPC:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterPrivateSubnets:
    Type: List<String>
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentCloudTrailSNSTopic:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud

  SysdigSecureAPIToken:
    Type: String
    NoEcho: true
  SysdigSecureEndpoint:
    Type: String
    Default: "https://secure.sysdig.com"
  SysdigRoleName:
    Type: String
    Default: "SysdigAgentlessRole"
  SysdigExternalID:
    Type: String
    Default: ""
  SysdigTrustedIdentity:
    Type: String
    Default: ""

  CreateSysdigRole:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"

Conditions:
  RequiresCloudTrail: !Equals [!Ref ExistentCloudTrailSNSTopic, ""]
  RequiresNewECSCluster: !Or
    - !Equals [!Ref ExistentECSCluster, ""]
    - !Equals [!Ref ExistentECSClusterVPC, ""]
    - !Equals [!Join [",", !Ref ExistentECSClusterPrivateSubnets], ""]
  DeployCloudConnector: !Equals [!Ref CloudConnectorDeploy, "Yes"]
  DeployCloudScanning: !Or
    - !Equals [!Ref ECRImageScanningDeploy, "Yes"]
    - !Equals [!Ref ECSImageScanningDeploy, "Yes"]
  DeployCloudTrail: !And
    - !Condition RequiresCloudTrail
    - !Or
      - !Condition DeployCloudConnector
      - !Condition DeployCloudScanning
  DeployNewECSCluster: !And
    - !Condition RequiresNewECSCluster
    - !Or
      - !Condition DeployCloudConnector
      - !Condition DeployCloudScanning
  EndpointIsSaas: !Or
    - !Equals [!Ref SysdigSecureEndpoint, "https://secure.sysdig.com"]
    - !Equals [!Ref SysdigSecureEndpoint, "https://eu1.app.sysdig.com"]
    - !Equals [!Ref SysdigSecureEndpoint, "https://us2.app.sysdig.com"]
  RequireSysdigRole: !Equals [ !Ref CreateSysdigRole, "Yes" ]

Resources:
  S3ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref SysdigConfigLoggingBucket
        LogFilePrefix: sysdig-config-bucket-logs
  SysdigConfigLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SysdigSecureAPITokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Sysdig Secure API Token"
      Type: String
      Value: !Ref SysdigSecureAPIToken

  SysdigSecureEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Sysdig Secure Endpoint URL"
      Type: String
      Value: !Ref SysdigSecureEndpoint

  ECSFargateClusterStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployNewECSCluster
    Properties:
      TemplateURL: ./ECSFargateCluster.yaml

  CloudTrailStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudTrail
    Properties:
      TemplateURL: ./CloudTrail.yaml

  CloudConnectorStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudConnector
    Properties:
      TemplateURL: ./CloudConnector.yaml
      Parameters:
        ECSCluster: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.ClusterName"], !Ref ExistentECSCluster ]
        VPC: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.VPC"], !Ref ExistentECSClusterVPC ]
        Subnets: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.PrivateSubnets"], !Join [",", !Ref ExistentECSClusterPrivateSubnets] ]
        SysdigSecureEndpointSsm: !Ref SysdigSecureEndpointParameter
        SysdigSecureAPITokenSsm: !Ref SysdigSecureAPITokenParameter
        S3ConfigBucket: !Ref S3ConfigBucket
        VerifySSL: !If [ EndpointIsSaas, "Yes", "No" ]
        CloudTrailTopic: !If [ DeployCloudTrail, !GetAtt ["CloudTrailStack", "Outputs.Topic"], !Ref ExistentCloudTrailSNSTopic ]

  ScanningCodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudScanning
    Properties:
      TemplateURL: ./ScanningCodeBuild.yaml
      Parameters:
        SysdigSecureEndpointSsm: !Ref SysdigSecureEndpointParameter
        SysdigSecureAPITokenSsm: !Ref SysdigSecureAPITokenParameter
        VerifySSL: !If [ EndpointIsSaas, "Yes", "No" ]

  CloudScanningStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudScanning
    Properties:
      TemplateURL: ./CloudScanning.yaml
      Parameters:
        ECSCluster: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.ClusterName"], !Ref ExistentECSCluster ]
        VPC: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.VPC"], !Ref ExistentECSClusterVPC ]
        Subnets: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.PrivateSubnets"], !Join [",", !Ref ExistentECSClusterPrivateSubnets] ]
        SysdigSecureEndpointSsm: !Ref SysdigSecureEndpointParameter
        SysdigSecureAPITokenSsm: !Ref SysdigSecureAPITokenParameter
        VerifySSL: !If [ EndpointIsSaas, "Yes", "No" ]
        ECRDeployed: !Ref ECRImageScanningDeploy
        ECSDeployed: !Ref ECSImageScanningDeploy
        BuildProject: !GetAtt [ "ScanningCodeBuildStack", "Outputs.BuildProject" ]
        CloudTrailTopic: !If [ DeployCloudTrail, !GetAtt ["CloudTrailStack", "Outputs.Topic"], !Ref ExistentCloudTrailSNSTopic ]

  CloudAgentlessRole:
    Type: AWS::CloudFormation::Stack
    Condition: RequireSysdigRole
    Properties:
      TemplateURL: ./CloudAgentlessRole.yaml
      Parameters:
        SysdigRoleName: !Ref SysdigRoleName
        SysdigExternalID: !Ref SysdigExternalID
        SysdigTrustedIdentity: !Ref SysdigTrustedIdentity