AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig for Cloud - AWS Edition

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings"
        Parameters:
          - SysdigSecureEndpoint
          - SysdigSecureAPIToken

      - Label:
          default: "Modules to Deploy"
        Parameters:
          - CloudBenchDeploy
          - CloudConnectorDeploy
          - ECRImageScanningDeploy
          - ECSImageScanningDeploy

      - Label:
          default: "Existing Infrastructure"
        Parameters:
          - ExistentECSCluster
          - ExistentECSClusterVPC
          - ExistentECSClusterPrivateSubnets

    ParameterLabels:
      SysdigSecureEndpoint:
        default: "Sysdig Secure Endpoint"
      SysdigSecureAPIToken:
        default: "Sysdig Secure API Token"
      CloudBenchDeploy:
        default: "Do you want to deploy Cloud Security Posture Management / Compliance?"
      CloudConnectorDeploy:
        default: "Do you want to deploy Real-Time Threat Investigation based on CloudTrail?"
      ECRImageScanningDeploy:
        default: "Do you want to deploy ECR Image Registry Scanning?"
      ECSImageScanningDeploy:
        default: "Do you want to deploy Fargate Image Scanning?"
      ExistentECSCluster:
        default: "ECS Cluster Name"
      ExistentECSClusterVPC:
        default: "VPC Id"
      ExistentECSClusterPrivateSubnets:
        default: "Private subnet Id's"

Parameters:
  CloudBenchDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  CloudConnectorDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECRImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECSImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ExistentECSCluster:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterVPC:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterPrivateSubnets:
    Type: List<String>
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud

  SysdigSecureAPIToken:
    Type: String
    NoEcho: true
  SysdigSecureEndpoint:
    Type: String
    Default: "https://secure.sysdig.com"

Conditions:
  DeployECRImageScanning: !Equals [!Ref ECRImageScanningDeploy, "Yes"]
  DeployECSImageScanning: !Equals [!Ref ECSImageScanningDeploy, "Yes"]
  DeployCloudScanning: !Or [!Condition DeployECRImageScanning, !Condition DeployECSImageScanning]
  DeployCloudConnector: !Equals [!Ref CloudConnectorDeploy, "Yes"]
  DeployCloudBench: !Equals [ !Ref CloudBenchDeploy, "Yes" ]
  DeployCloudTrail: !Or [!Condition DeployCloudScanning, !Condition DeployCloudConnector]
  RequiresNewECSCluster:
    Fn::Or:
      - Fn::Equals:
        - !Ref ExistentECSCluster
        - ""
      - Fn::Equals:
        - !Ref ExistentECSClusterVPC
        - ""
      - Fn::Equals:
        - !Join [",", !Ref ExistentECSClusterPrivateSubnets]
        - ""
  DeployNewECSCluster: !And
       - !Or
         - !Condition DeployCloudConnector
         - !Condition DeployCloudBench
         - !Condition DeployCloudScanning
       - !Condition RequiresNewECSCluster
  EndpointIsSaas:
    Fn::Or:
      - Fn::Equals:
        - !Ref SysdigSecureEndpoint
        - "https://secure.sysdig.com"
      - Fn::Equals:
        - !Ref SysdigSecureEndpoint
        - "https://eu1.app.sysdig.com"
      - Fn::Equals:
        - !Ref SysdigSecureEndpoint
        - "https://us2.app.sysdig.com"

Resources:
  S3ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  SysdigSecureAPITokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Sysdig Secure API Token"
      Type: String
      Value: !Ref SysdigSecureAPIToken

  SysdigSecureEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Sysdig Secure Endpoint URL"
      Type: String
      Value: !Ref SysdigSecureEndpoint

  ECSFargateClusterStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployNewECSCluster
    Properties:
      TemplateURL: ./ECSFargateCluster.yaml

  CloudTrailStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudTrail
    Properties:
      TemplateURL: ./CloudTrail.yaml

  CloudConnectorStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudConnector
    Properties:
      TemplateURL: ./CloudConnector.yaml
      Parameters:
        ECSCluster: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.ClusterName"], !Ref ExistentECSCluster ]
        VPC: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.VPC"], !Ref ExistentECSClusterVPC ]
        Subnets: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.PrivateSubnets"], !Join [",", !Ref ExistentECSClusterPrivateSubnets] ]
        SysdigSecureEndpointSsm: !Ref SysdigSecureEndpointParameter
        SysdigSecureAPITokenSsm: !Ref SysdigSecureAPITokenParameter
        S3ConfigBucket: !Ref S3ConfigBucket
        VerifySSL: !If [ EndpointIsSaas, "Yes", "No" ]
        CloudBenchDeployed: !Ref CloudBenchDeploy
        ECRDeployed: !Ref ECRImageScanningDeploy
        ECSDeployed: !Ref ECSImageScanningDeploy
        CloudTrailTopic: !GetAtt ["CloudTrailStack", "Outputs.Topic"]

  ScanningCodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudScanning
    Properties:
      TemplateURL: ./ScanningCodeBuild.yaml
      Parameters:
        SysdigSecureEndpointSsm: !Ref SysdigSecureEndpointParameter
        SysdigSecureAPITokenSsm: !Ref SysdigSecureAPITokenParameter
        VerifySSL: !If [ EndpointIsSaas, "Yes", "No" ]

  CloudScanningStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudScanning
    Properties:
      TemplateURL: ./CloudScanning.yaml
      Parameters:
        ECSCluster: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.ClusterName"], !Ref ExistentECSCluster ]
        VPC: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.VPC"], !Ref ExistentECSClusterVPC ]
        Subnets: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.PrivateSubnets"], !Join [",", !Ref ExistentECSClusterPrivateSubnets] ]
        SysdigSecureEndpointSsm: !Ref SysdigSecureEndpointParameter
        SysdigSecureAPITokenSsm: !Ref SysdigSecureAPITokenParameter
        ECRDeployed: !Ref ECRImageScanningDeploy
        ECSDeployed: !Ref ECSImageScanningDeploy
        BuildProject: !GetAtt [ "ScanningCodeBuildStack", "Outputs.BuildProject" ]
        CloudTrailTopic: !GetAtt ["CloudTrailStack", "Outputs.Topic"]

  CloudBenchStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudBench
    Properties:
      TemplateURL: ./CloudBench.yaml
      Parameters:
        ECSCluster: !If [ DeployNewECSCluster, !GetAtt [ "ECSFargateClusterStack", "Outputs.ClusterName" ], !Ref ExistentECSCluster ]
        VPC: !If [ DeployNewECSCluster, !GetAtt [ "ECSFargateClusterStack", "Outputs.VPC" ], !Ref ExistentECSClusterVPC ]
        Subnets: !If [ DeployNewECSCluster, !GetAtt [ "ECSFargateClusterStack", "Outputs.PrivateSubnets" ], !Join [ ",", !Ref ExistentECSClusterPrivateSubnets ] ]
        SysdigSecureEndpointSsm: !Ref SysdigSecureEndpointParameter
        SysdigSecureAPITokenSsm: !Ref SysdigSecureAPITokenParameter
        S3ConfigBucket: !Ref S3ConfigBucket
        VerifySSL: !If [ EndpointIsSaas, "Yes", "No" ]
