AWSTemplateFormatVersion: "2010-09-09"
Description: Fargate Cluster where Sysdig CloudVision apps are deployed

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./VPC.yaml

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AWS::StackName}"

Outputs:
  ClusterName:
    Description: Cluster name for Sysdig CloudVision workload
    Value: !Ref ECSCluster

  VPC:
    Description: The VPC ID
    Value: !GetAtt ["VPCStack", "Outputs.VPC"]

  PublicSubnets:
    Description: Public Subnets
    Value: !GetAtt ["VPCStack", "Outputs.PublicSubnets"]

  PrivateSubnets:
    Description: Private Subnets
    Value: !GetAtt ["VPCStack", "Outputs.PrivateSubnets"]
