Resources:
  CloudTraiResources:lBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref CloudTrailLogRetention
            Status: Enabled
      AccessControl: PublicReadWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref CloudTrailLoggingBucket
        LogFilePrefix: sysdig-cloudtrail-bucket-logs
