AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Roles for CSPM and Cloudlogs used by Sysdig Secure

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings (Do not change)"
        Parameters:
          - CSPMRoleName
          - CloudLogsRoleName
          - ExternalID
          - TrustedIdentity
          - BucketARN
          - CreateTopic
          - TopicARN
          - Endpoint

    ParameterLabels:
      CSPMRoleName:
        default: "CSPM Role Name (Sysdig use only)"
      CloudLogsRoleName:
        default: "CloudLogs Role Name (Sysdig use only)"
      ExternalID:
        default: "External ID (Sysdig use only)"
      TrustedIdentity:
        default: "Trusted Identity (Sysdig use only)"
      BucketARN:
        default: "Bucket ARN"
      CreateTopic:
        default: "Create SNS Topic"
      TopicARN:
        default: "SNS Topic ARN"
      Endpoint:
        default: "Sysdig Secure endpoint"

Parameters:
  CSPMRoleName:
    Type: String
    Description: The read-only IAM Role that Sysdig will create

  CloudLogsRoleName:
    Type: String
    Description: The name of the IAM Role that will enable access to the Cloudtrail logs.

  ExternalID:
    Type: String
    Description: Sysdig ExternalID required for the policy creation

  TrustedIdentity:
    Type: String
    Description: The name of Sysdig trusted identity.

  BucketARN:
    Type: String
    Description: The ARN of your S3 bucket associated with your CloudTrail trail.

  CreateTopic:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description: "Whether to create a new SNS Topic for CloudTrail notifications."

  TopicARN:
    Type: String
    Default: ""
    Description: "The ARN of an existing SNS Topic. If CreateTopic is true, this will be used as the name of the new topic."

  Endpoint:
    Type: String
    Default: ""
    Description: "Sysdig Secure endpoint to receive CloudTrail notifications."

Resources:
  CloudAgentlessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref CSPMRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: !Ref TrustedIdentity
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalID
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Policies:
        - PolicyName: !Ref CSPMRoleName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "elasticfilesystem:DescribeAccessPoints"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "waf-regional:ListRules"
                  - "waf-regional:ListRuleGroups"
                Resource:
                  - "arn:aws:waf-regional:*:*:rule/*"
                  - "arn:aws:waf-regional:*:*:rulegroup/*"
              - Effect: "Allow"
                Action: "macie2:ListClassificationJobs"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "lambda:GetRuntimeManagementConfig"
                  - "lambda:GetFunction"
                Resource: "*"
              - Effect: "Allow"
                Action: "account:GetContactInformation"
                Resource: "*"
  CloudLogsRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref CloudLogsRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Ref TrustedIdentity
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref ExternalID

  # IAM Policy
  CloudLogsRolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "CloudlogsS3Access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "CloudlogsS3AccessGet"
            Effect: "Allow"
            Action:
              - "s3:Get*"
            Resource:
              - !Sub '${BucketARN}'
              - !Sub '${BucketARN}/*'
          - Sid: "CloudlogsS3AccessList"
            Effect: "Allow"
            Action:
              - "s3:List*"
            Resource:
              - !Sub '${BucketARN}'
              - !Sub '${BucketARN}/*'
      Roles:
        - !Ref CloudLogsRole

  CloudTrailNotificationsTopic:
    Condition: CreateSNSTopic
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Select [ 5, !Split [ ":", !Ref TopicARN ] ]

  CloudTrailNotificationsSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !If [ CreateSNSTopic, !Ref CloudTrailNotificationsTopic, !Ref TopicARN ]
      Protocol: "https"
      Endpoint: !Ref Endpoint

  CloudTrailNotificationsPolicy:
    Condition: CreateSNSTopic
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - !Ref CloudTrailNotificationsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudTrailPublish"
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "SNS:Publish"
            Resource: !Ref CloudTrailNotificationsTopic

Conditions:
  CreateSNSTopic: !Equals [ !Ref CreateTopic, "true" ]

Outputs:
  RoleARN:
    Description: "The ARN of the IAM Role created for CloudTrail logs."
    Value: !GetAtt CloudLogsRole.Arn

  TopicARN:
    Description: "The ARN of the SNS Topic created for CloudTrail notifications."
    Value: !If [ CreateSNSTopic, !Ref CloudTrailNotificationsTopic, !Ref TopicARN ]
