name: CI - Cloud IAC Scanner

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  iac-scanner:
    name: Cloud IAC Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cloud IAC parser
        uses: sysdiglabs/cloud-iac-scanner-action@v0.0.13
        with:
          parser: 'cloudformation'
        id: iac-scanner
      - name: Print output
        shell: bash
        run: |
          echo ${{steps.iac-scanner.outputs.scanner-output}} | sed 1,2d | while read line; do echo "$line"; done