name: CI - Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
        echo "${GITHUB_HEAD_REF#refs/heads/}"
        echo "${{ github.event.pull_request.head.ref }}"
      id: extract_branch
