name: Release AppRunner

on:
  push:
    tags:
      - v*
    paths:
      - 'templates_apprunner/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Setup go-chglog
      run: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog

    - name: Generate changelog
      run: git-chglog -c .github/git-chglog/config.yml -o RELEASE_CHANGELOG.md $(git describe --tags $(git rev-list --tags --max-count=1))

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false
        body_path: RELEASE_CHANGELOG.md

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Prepare
      id: prep
      run: |
        echo ::set-output name=VERSION::$(echo "${{ github.ref }}" | sed -e 's/.*\/v\(.*\)/\1/')

    - name: Build and Upload AppRunner Version
      run: make ci
      working-directory: ./templates_apprunner
      env:
        S3_BUCKET: cf-templates-cloudvision-ci
        S3_PREFIX: ${{ steps.prep.outputs.VERSION }}

    - name: Build and Upload AppRunner Latest
      run: make ci
      working-directory: ./templates_apprunner
      env:
        S3_BUCKET: cf-templates-cloudvision-ci
        S3_PREFIX: latest
